// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.24.3
// source: pkg/cluster/dbpb/db.proto

package dbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DB_REQUEST_TYPE int32

const (
	DB_REQUEST_TYPE_Z_ADD            DB_REQUEST_TYPE = 0
	DB_REQUEST_TYPE_Z_DELETE         DB_REQUEST_TYPE = 1
	DB_REQUEST_TYPE_Z_RANGE          DB_REQUEST_TYPE = 2
	DB_REQUEST_TYPE_Z_RANGE_BY_SCORE DB_REQUEST_TYPE = 3
	DB_REQUEST_TYPE_PUT              DB_REQUEST_TYPE = 110
	DB_REQUEST_TYPE_GET              DB_REQUEST_TYPE = 111
	DB_REQUEST_TYPE_DELETE           DB_REQUEST_TYPE = 112
	DB_REQUEST_TYPE_GET_PREFIX       DB_REQUEST_TYPE = 113
	DB_REQUEST_TYPE_DELETE_PREFIX    DB_REQUEST_TYPE = 114
	DB_REQUEST_TYPE_INCR             DB_REQUEST_TYPE = 115
	DB_REQUEST_TYPE_DECR             DB_REQUEST_TYPE = 116
	DB_REQUEST_TYPE_HSET             DB_REQUEST_TYPE = 220
	DB_REQUEST_TYPE_HGET             DB_REQUEST_TYPE = 221
	DB_REQUEST_TYPE_HDEL             DB_REQUEST_TYPE = 222
	DB_REQUEST_TYPE_HGET_ALL         DB_REQUEST_TYPE = 223
	DB_REQUEST_TYPE_HGET_PREFIX      DB_REQUEST_TYPE = 224
	DB_REQUEST_TYPE_DELETE_HASH      DB_REQUEST_TYPE = 225
	DB_REQUEST_TYPE_EXPIRE           DB_REQUEST_TYPE = 226
)

// Enum value maps for DB_REQUEST_TYPE.
var (
	DB_REQUEST_TYPE_name = map[int32]string{
		0:   "Z_ADD",
		1:   "Z_DELETE",
		2:   "Z_RANGE",
		3:   "Z_RANGE_BY_SCORE",
		110: "PUT",
		111: "GET",
		112: "DELETE",
		113: "GET_PREFIX",
		114: "DELETE_PREFIX",
		115: "INCR",
		116: "DECR",
		220: "HSET",
		221: "HGET",
		222: "HDEL",
		223: "HGET_ALL",
		224: "HGET_PREFIX",
		225: "DELETE_HASH",
		226: "EXPIRE",
	}
	DB_REQUEST_TYPE_value = map[string]int32{
		"Z_ADD":            0,
		"Z_DELETE":         1,
		"Z_RANGE":          2,
		"Z_RANGE_BY_SCORE": 3,
		"PUT":              110,
		"GET":              111,
		"DELETE":           112,
		"GET_PREFIX":       113,
		"DELETE_PREFIX":    114,
		"INCR":             115,
		"DECR":             116,
		"HSET":             220,
		"HGET":             221,
		"HDEL":             222,
		"HGET_ALL":         223,
		"HGET_PREFIX":      224,
		"DELETE_HASH":      225,
		"EXPIRE":           226,
	}
)

func (x DB_REQUEST_TYPE) Enum() *DB_REQUEST_TYPE {
	p := new(DB_REQUEST_TYPE)
	*p = x
	return p
}

func (x DB_REQUEST_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DB_REQUEST_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cluster_dbpb_db_proto_enumTypes[0].Descriptor()
}

func (DB_REQUEST_TYPE) Type() protoreflect.EnumType {
	return &file_pkg_cluster_dbpb_db_proto_enumTypes[0]
}

func (x DB_REQUEST_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DB_REQUEST_TYPE.Descriptor instead.
func (DB_REQUEST_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cluster_dbpb_db_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type     DB_REQUEST_TYPE `protobuf:"varint,2,opt,name=Type,proto3,enum=dbpb.DB_REQUEST_TYPE" json:"Type,omitempty"`
	CMD      [][]byte        `protobuf:"bytes,3,rep,name=CMD,proto3" json:"CMD,omitempty"`
	Bucket   string          `protobuf:"bytes,4,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	TtlNanos int64           `protobuf:"varint,5,opt,name=ttl_nanos,json=ttlNanos,proto3" json:"ttl_nanos,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cluster_dbpb_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_dbpb_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_dbpb_db_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Request) GetType() DB_REQUEST_TYPE {
	if x != nil {
		return x.Type
	}
	return DB_REQUEST_TYPE_Z_ADD
}

func (x *Request) GetCMD() [][]byte {
	if x != nil {
		return x.CMD
	}
	return nil
}

func (x *Request) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Request) GetTtlNanos() int64 {
	if x != nil {
		return x.TtlNanos
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type    DB_REQUEST_TYPE `protobuf:"varint,2,opt,name=Type,proto3,enum=dbpb.DB_REQUEST_TYPE" json:"Type,omitempty"`
	Success bool            `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	Result  [][]byte        `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	Exist   bool            `protobuf:"varint,5,opt,name=Exist,proto3" json:"Exist,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cluster_dbpb_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_dbpb_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_dbpb_db_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Response) GetType() DB_REQUEST_TYPE {
	if x != nil {
		return x.Type
	}
	return DB_REQUEST_TYPE_Z_ADD
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetResult() [][]byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

var File_pkg_cluster_dbpb_db_proto protoreflect.FileDescriptor

var file_pkg_cluster_dbpb_db_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x64, 0x62,
	0x70, 0x62, 0x2f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x62, 0x70,
	0x62, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x29, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x64, 0x62,
	0x70, 0x62, 0x2e, 0x44, 0x42, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x4d, 0x44, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x43, 0x4d, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x74, 0x6c, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x74, 0x6c, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x22,
	0x8d, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x64, 0x62, 0x70,
	0x62, 0x2e, 0x44, 0x42, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x45, 0x78, 0x69, 0x73, 0x74, 0x2a,
	0x83, 0x02, 0x0a, 0x0f, 0x44, 0x42, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x12, 0x09, 0x0a, 0x05, 0x5a, 0x5f, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x5a, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x5a, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x5a, 0x5f, 0x52,
	0x41, 0x4e, 0x47, 0x45, 0x5f, 0x42, 0x59, 0x5f, 0x53, 0x43, 0x4f, 0x52, 0x45, 0x10, 0x03, 0x12,
	0x07, 0x0a, 0x03, 0x50, 0x55, 0x54, 0x10, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10,
	0x6f, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x70, 0x12, 0x0e, 0x0a,
	0x0a, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10, 0x71, 0x12, 0x11, 0x0a,
	0x0d, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10, 0x72,
	0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x43, 0x52, 0x10, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45,
	0x43, 0x52, 0x10, 0x74, 0x12, 0x09, 0x0a, 0x04, 0x48, 0x53, 0x45, 0x54, 0x10, 0xdc, 0x01, 0x12,
	0x09, 0x0a, 0x04, 0x48, 0x47, 0x45, 0x54, 0x10, 0xdd, 0x01, 0x12, 0x09, 0x0a, 0x04, 0x48, 0x44,
	0x45, 0x4c, 0x10, 0xde, 0x01, 0x12, 0x0d, 0x0a, 0x08, 0x48, 0x47, 0x45, 0x54, 0x5f, 0x41, 0x4c,
	0x4c, 0x10, 0xdf, 0x01, 0x12, 0x10, 0x0a, 0x0b, 0x48, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x45,
	0x46, 0x49, 0x58, 0x10, 0xe0, 0x01, 0x12, 0x10, 0x0a, 0x0b, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x5f, 0x48, 0x41, 0x53, 0x48, 0x10, 0xe1, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x45, 0x58, 0x50, 0x49,
	0x52, 0x45, 0x10, 0xe2, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x41, 0x4e, 0x31, 0x63, 0x65, 0x2f, 0x73, 0x6b, 0x79, 0x54, 0x72,
	0x65, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x64,
	0x62, 0x70, 0x62, 0x3b, 0x64, 0x62, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_cluster_dbpb_db_proto_rawDescOnce sync.Once
	file_pkg_cluster_dbpb_db_proto_rawDescData = file_pkg_cluster_dbpb_db_proto_rawDesc
)

func file_pkg_cluster_dbpb_db_proto_rawDescGZIP() []byte {
	file_pkg_cluster_dbpb_db_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_dbpb_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_cluster_dbpb_db_proto_rawDescData)
	})
	return file_pkg_cluster_dbpb_db_proto_rawDescData
}

var file_pkg_cluster_dbpb_db_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_cluster_dbpb_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_cluster_dbpb_db_proto_goTypes = []interface{}{
	(DB_REQUEST_TYPE)(0), // 0: dbpb.DB_REQUEST_TYPE
	(*Request)(nil),      // 1: dbpb.Request
	(*Response)(nil),     // 2: dbpb.Response
}
var file_pkg_cluster_dbpb_db_proto_depIdxs = []int32{
	0, // 0: dbpb.Request.Type:type_name -> dbpb.DB_REQUEST_TYPE
	0, // 1: dbpb.Response.Type:type_name -> dbpb.DB_REQUEST_TYPE
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_cluster_dbpb_db_proto_init() }
func file_pkg_cluster_dbpb_db_proto_init() {
	if File_pkg_cluster_dbpb_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_cluster_dbpb_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cluster_dbpb_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_cluster_dbpb_db_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_cluster_dbpb_db_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_dbpb_db_proto_depIdxs,
		EnumInfos:         file_pkg_cluster_dbpb_db_proto_enumTypes,
		MessageInfos:      file_pkg_cluster_dbpb_db_proto_msgTypes,
	}.Build()
	File_pkg_cluster_dbpb_db_proto = out.File
	file_pkg_cluster_dbpb_db_proto_rawDesc = nil
	file_pkg_cluster_dbpb_db_proto_goTypes = nil
	file_pkg_cluster_dbpb_db_proto_depIdxs = nil
}
