// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: close_client.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseClientRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ClientID     string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	NodeID       uint64                 `protobuf:"varint,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	SessionClean bool                   `protobuf:"varint,3,opt,name=SessionClean,proto3" json:"SessionClean,omitempty"`
	// OwnerToken is a fencing token (UUID string). The server must only close the client
	// if the current active connection's token matches this value.
	OwnerToken    string `protobuf:"bytes,4,opt,name=OwnerToken,proto3" json:"OwnerToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseClientRequest) Reset() {
	*x = CloseClientRequest{}
	mi := &file_close_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseClientRequest) ProtoMessage() {}

func (x *CloseClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_close_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseClientRequest.ProtoReflect.Descriptor instead.
func (*CloseClientRequest) Descriptor() ([]byte, []int) {
	return file_close_client_proto_rawDescGZIP(), []int{0}
}

func (x *CloseClientRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *CloseClientRequest) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *CloseClientRequest) GetSessionClean() bool {
	if x != nil {
		return x.SessionClean
	}
	return false
}

func (x *CloseClientRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

type CloseClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseClientResponse) Reset() {
	*x = CloseClientResponse{}
	mi := &file_close_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseClientResponse) ProtoMessage() {}

func (x *CloseClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_close_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseClientResponse.ProtoReflect.Descriptor instead.
func (*CloseClientResponse) Descriptor() ([]byte, []int) {
	return file_close_client_proto_rawDescGZIP(), []int{1}
}

func (x *CloseClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_close_client_proto protoreflect.FileDescriptor

const file_close_client_proto_rawDesc = "" +
	"\n" +
	"\x12close_client.proto\x12\x05proto\"\x8c\x01\n" +
	"\x12CloseClientRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\x16\n" +
	"\x06NodeID\x18\x02 \x01(\x04R\x06NodeID\x12\"\n" +
	"\fSessionClean\x18\x03 \x01(\bR\fSessionClean\x12\x1e\n" +
	"\n" +
	"OwnerToken\x18\x04 \x01(\tR\n" +
	"OwnerToken\"I\n" +
	"\x13CloseClientResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage2T\n" +
	"\fClientCenter\x12D\n" +
	"\vCloseClient\x12\x19.proto.CloseClientRequest\x1a\x1a.proto.CloseClientResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_close_client_proto_rawDescOnce sync.Once
	file_close_client_proto_rawDescData []byte
)

func file_close_client_proto_rawDescGZIP() []byte {
	file_close_client_proto_rawDescOnce.Do(func() {
		file_close_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_close_client_proto_rawDesc), len(file_close_client_proto_rawDesc)))
	})
	return file_close_client_proto_rawDescData
}

var file_close_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_close_client_proto_goTypes = []any{
	(*CloseClientRequest)(nil),  // 0: proto.CloseClientRequest
	(*CloseClientResponse)(nil), // 1: proto.CloseClientResponse
}
var file_close_client_proto_depIdxs = []int32{
	0, // 0: proto.ClientCenter.CloseClient:input_type -> proto.CloseClientRequest
	1, // 1: proto.ClientCenter.CloseClient:output_type -> proto.CloseClientResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_close_client_proto_init() }
func file_close_client_proto_init() {
	if File_close_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_close_client_proto_rawDesc), len(file_close_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_close_client_proto_goTypes,
		DependencyIndexes: file_close_client_proto_depIdxs,
		MessageInfos:      file_close_client_proto_msgTypes,
	}.Build()
	File_close_client_proto = out.File
	file_close_client_proto_goTypes = nil
	file_close_client_proto_depIdxs = nil
}
