// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: close_client.proto

package nodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// NOTE: Patched for repository grpc-go version compatibility.
const _ = grpc.SupportPackageIsVersion8

const (
	ClientCenter_CloseClient_FullMethodName = "/proto.ClientCenter/CloseClient"
)

// ClientCenterClient is the client API for ClientCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientCenterClient interface {
	CloseClient(ctx context.Context, in *CloseClientRequest, opts ...grpc.CallOption) (*CloseClientResponse, error)
}

type clientCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewClientCenterClient(cc grpc.ClientConnInterface) ClientCenterClient {
	return &clientCenterClient{cc}
}

func (c *clientCenterClient) CloseClient(ctx context.Context, in *CloseClientRequest, opts ...grpc.CallOption) (*CloseClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseClientResponse)
	err := c.cc.Invoke(ctx, ClientCenter_CloseClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientCenterServer is the server API for ClientCenter service.
// All implementations must embed UnimplementedClientCenterServer
// for forward compatibility.
type ClientCenterServer interface {
	CloseClient(context.Context, *CloseClientRequest) (*CloseClientResponse, error)
	mustEmbedUnimplementedClientCenterServer()
}

// UnimplementedClientCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientCenterServer struct{}

func (UnimplementedClientCenterServer) CloseClient(context.Context, *CloseClientRequest) (*CloseClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseClient not implemented")
}
func (UnimplementedClientCenterServer) mustEmbedUnimplementedClientCenterServer() {}
func (UnimplementedClientCenterServer) testEmbeddedByValue()                      {}

// UnsafeClientCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientCenterServer will
// result in compilation errors.
type UnsafeClientCenterServer interface {
	mustEmbedUnimplementedClientCenterServer()
}

func RegisterClientCenterServer(s grpc.ServiceRegistrar, srv ClientCenterServer) {
	// If the following call pancis, it indicates UnimplementedClientCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientCenter_ServiceDesc, srv)
}

func _ClientCenter_CloseClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCenterServer).CloseClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientCenter_CloseClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCenterServer).CloseClient(ctx, req.(*CloseClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientCenter_ServiceDesc is the grpc.ServiceDesc for ClientCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ClientCenter",
	HandlerType: (*ClientCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseClient",
			Handler:    _ClientCenter_CloseClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "close_client.proto",
}
