// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: notify_client_delivery.proto

package nodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientDeliveryNotify_Notify_FullMethodName = "/nodepb.ClientDeliveryNotify/Notify"
)

// ClientDeliveryNotifyClient is the client API for ClientDeliveryNotify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientDeliveryNotify is the node-to-node notification service for client delivery events.
type ClientDeliveryNotifyClient interface {
	Notify(ctx context.Context, in *ClientDeliveryNotifyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientDeliveryNotifyClient struct {
	cc grpc.ClientConnInterface
}

func NewClientDeliveryNotifyClient(cc grpc.ClientConnInterface) ClientDeliveryNotifyClient {
	return &clientDeliveryNotifyClient{cc}
}

func (c *clientDeliveryNotifyClient) Notify(ctx context.Context, in *ClientDeliveryNotifyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientDeliveryNotify_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientDeliveryNotifyServer is the server API for ClientDeliveryNotify service.
// All implementations must embed UnimplementedClientDeliveryNotifyServer
// for forward compatibility.
//
// ClientDeliveryNotify is the node-to-node notification service for client delivery events.
type ClientDeliveryNotifyServer interface {
	Notify(context.Context, *ClientDeliveryNotifyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedClientDeliveryNotifyServer()
}

// UnimplementedClientDeliveryNotifyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientDeliveryNotifyServer struct{}

func (UnimplementedClientDeliveryNotifyServer) Notify(context.Context, *ClientDeliveryNotifyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedClientDeliveryNotifyServer) mustEmbedUnimplementedClientDeliveryNotifyServer() {}
func (UnimplementedClientDeliveryNotifyServer) testEmbeddedByValue()                              {}

// UnsafeClientDeliveryNotifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientDeliveryNotifyServer will
// result in compilation errors.
type UnsafeClientDeliveryNotifyServer interface {
	mustEmbedUnimplementedClientDeliveryNotifyServer()
}

func RegisterClientDeliveryNotifyServer(s grpc.ServiceRegistrar, srv ClientDeliveryNotifyServer) {
	// If the following call pancis, it indicates UnimplementedClientDeliveryNotifyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientDeliveryNotify_ServiceDesc, srv)
}

func _ClientDeliveryNotify_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDeliveryNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientDeliveryNotifyServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientDeliveryNotify_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientDeliveryNotifyServer).Notify(ctx, req.(*ClientDeliveryNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientDeliveryNotify_ServiceDesc is the grpc.ServiceDesc for ClientDeliveryNotify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientDeliveryNotify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodepb.ClientDeliveryNotify",
	HandlerType: (*ClientDeliveryNotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _ClientDeliveryNotify_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify_client_delivery.proto",
}
