// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: notify_client_delivery.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientDeliveryNotifyKind int32

const (
	ClientDeliveryNotifyKind_CLIENT_DELIVERY_NOTIFY_KIND_UNSPECIFIED ClientDeliveryNotifyKind = 0
	// Wake tells the target node to wake the client delivery runner and re-check store (with backoff).
	ClientDeliveryNotifyKind_CLIENT_DELIVERY_NOTIFY_KIND_WAKE ClientDeliveryNotifyKind = 1
	// Qos0Direct carries an encoded broker publish message for direct QoS0 delivery without persistence.
	ClientDeliveryNotifyKind_CLIENT_DELIVERY_NOTIFY_KIND_QOS0_DIRECT ClientDeliveryNotifyKind = 2
	// SharedWake tells the target node to wake the shared subscription consumer for a share group.
	ClientDeliveryNotifyKind_CLIENT_DELIVERY_NOTIFY_KIND_SHARED_WAKE ClientDeliveryNotifyKind = 3
)

// Enum value maps for ClientDeliveryNotifyKind.
var (
	ClientDeliveryNotifyKind_name = map[int32]string{
		0: "CLIENT_DELIVERY_NOTIFY_KIND_UNSPECIFIED",
		1: "CLIENT_DELIVERY_NOTIFY_KIND_WAKE",
		2: "CLIENT_DELIVERY_NOTIFY_KIND_QOS0_DIRECT",
		3: "CLIENT_DELIVERY_NOTIFY_KIND_SHARED_WAKE",
	}
	ClientDeliveryNotifyKind_value = map[string]int32{
		"CLIENT_DELIVERY_NOTIFY_KIND_UNSPECIFIED": 0,
		"CLIENT_DELIVERY_NOTIFY_KIND_WAKE":        1,
		"CLIENT_DELIVERY_NOTIFY_KIND_QOS0_DIRECT": 2,
		"CLIENT_DELIVERY_NOTIFY_KIND_SHARED_WAKE": 3,
	}
)

func (x ClientDeliveryNotifyKind) Enum() *ClientDeliveryNotifyKind {
	p := new(ClientDeliveryNotifyKind)
	*p = x
	return p
}

func (x ClientDeliveryNotifyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientDeliveryNotifyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_client_delivery_proto_enumTypes[0].Descriptor()
}

func (ClientDeliveryNotifyKind) Type() protoreflect.EnumType {
	return &file_notify_client_delivery_proto_enumTypes[0]
}

func (x ClientDeliveryNotifyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientDeliveryNotifyKind.Descriptor instead.
func (ClientDeliveryNotifyKind) EnumDescriptor() ([]byte, []int) {
	return file_notify_client_delivery_proto_rawDescGZIP(), []int{0}
}

// ClientDeliveryOptions contains MQTT5 subscription options for a specific client.
type ClientDeliveryOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NoLocal: if true, do not deliver to the same client that published the message (MQTT5).
	NoLocal bool `protobuf:"varint,1,opt,name=NoLocal,proto3" json:"NoLocal,omitempty"`
	// RAP (Retain As Published): if false, force retain=0 for this delivery (MQTT5).
	RAP bool `protobuf:"varint,2,opt,name=RAP,proto3" json:"RAP,omitempty"`
	// SubscriptionIDsJSON: JSON array of subscription identifiers for matched subscriptions (MQTT5).
	SubscriptionIDsJSON string `protobuf:"bytes,3,opt,name=SubscriptionIDsJSON,proto3" json:"SubscriptionIDsJSON,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientDeliveryOptions) Reset() {
	*x = ClientDeliveryOptions{}
	mi := &file_notify_client_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeliveryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeliveryOptions) ProtoMessage() {}

func (x *ClientDeliveryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_notify_client_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeliveryOptions.ProtoReflect.Descriptor instead.
func (*ClientDeliveryOptions) Descriptor() ([]byte, []int) {
	return file_notify_client_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *ClientDeliveryOptions) GetNoLocal() bool {
	if x != nil {
		return x.NoLocal
	}
	return false
}

func (x *ClientDeliveryOptions) GetRAP() bool {
	if x != nil {
		return x.RAP
	}
	return false
}

func (x *ClientDeliveryOptions) GetSubscriptionIDsJSON() string {
	if x != nil {
		return x.SubscriptionIDsJSON
	}
	return ""
}

type ClientDeliveryNotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TargetNodeID is used for metrics/observability. Delivery is ensured by point-to-point dialing.
	TargetNodeID uint64 `protobuf:"varint,1,opt,name=TargetNodeID,proto3" json:"TargetNodeID,omitempty"`
	// ClientIDs are the target online clients on the node. Empty when Kind == SHARED_WAKE.
	ClientIDs []string `protobuf:"bytes,2,rep,name=ClientIDs,proto3" json:"ClientIDs,omitempty"`
	// Kind defines how the client runner should react.
	Kind ClientDeliveryNotifyKind `protobuf:"varint,3,opt,name=Kind,proto3,enum=nodepb.ClientDeliveryNotifyKind" json:"Kind,omitempty"`
	// Payload is optional. For QOS0_DIRECT it is bytes of proto_event.Request (Data=serializer(publish.Message)).
	// For SHARED_WAKE it is JSON bytes of SharedWakePayload.
	Payload []byte `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	// PublishTopic is optional, used for logs/metrics correlation.
	PublishTopic string `protobuf:"bytes,5,opt,name=PublishTopic,proto3" json:"PublishTopic,omitempty"`
	// ClientOptions maps clientID to MQTT5 subscription options (NoLocal, RAP). Only used when Kind == QOS0_DIRECT.
	ClientOptions map[string]*ClientDeliveryOptions `protobuf:"bytes,6,rep,name=ClientOptions,proto3" json:"ClientOptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeliveryNotifyRequest) Reset() {
	*x = ClientDeliveryNotifyRequest{}
	mi := &file_notify_client_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeliveryNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeliveryNotifyRequest) ProtoMessage() {}

func (x *ClientDeliveryNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_client_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeliveryNotifyRequest.ProtoReflect.Descriptor instead.
func (*ClientDeliveryNotifyRequest) Descriptor() ([]byte, []int) {
	return file_notify_client_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *ClientDeliveryNotifyRequest) GetTargetNodeID() uint64 {
	if x != nil {
		return x.TargetNodeID
	}
	return 0
}

func (x *ClientDeliveryNotifyRequest) GetClientIDs() []string {
	if x != nil {
		return x.ClientIDs
	}
	return nil
}

func (x *ClientDeliveryNotifyRequest) GetKind() ClientDeliveryNotifyKind {
	if x != nil {
		return x.Kind
	}
	return ClientDeliveryNotifyKind_CLIENT_DELIVERY_NOTIFY_KIND_UNSPECIFIED
}

func (x *ClientDeliveryNotifyRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientDeliveryNotifyRequest) GetPublishTopic() string {
	if x != nil {
		return x.PublishTopic
	}
	return ""
}

func (x *ClientDeliveryNotifyRequest) GetClientOptions() map[string]*ClientDeliveryOptions {
	if x != nil {
		return x.ClientOptions
	}
	return nil
}

var File_notify_client_delivery_proto protoreflect.FileDescriptor

const file_notify_client_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1cnotify_client_delivery.proto\x12\x06nodepb\x1a\x1bgoogle/protobuf/empty.proto\"u\n" +
	"\x15ClientDeliveryOptions\x12\x18\n" +
	"\aNoLocal\x18\x01 \x01(\bR\aNoLocal\x12\x10\n" +
	"\x03RAP\x18\x02 \x01(\bR\x03RAP\x120\n" +
	"\x13SubscriptionIDsJSON\x18\x03 \x01(\tR\x13SubscriptionIDsJSON\"\x92\x03\n" +
	"\x1bClientDeliveryNotifyRequest\x12\"\n" +
	"\fTargetNodeID\x18\x01 \x01(\x04R\fTargetNodeID\x12\x1c\n" +
	"\tClientIDs\x18\x02 \x03(\tR\tClientIDs\x124\n" +
	"\x04Kind\x18\x03 \x01(\x0e2 .nodepb.ClientDeliveryNotifyKindR\x04Kind\x12\x18\n" +
	"\aPayload\x18\x04 \x01(\fR\aPayload\x12\"\n" +
	"\fPublishTopic\x18\x05 \x01(\tR\fPublishTopic\x12\\\n" +
	"\rClientOptions\x18\x06 \x03(\v26.nodepb.ClientDeliveryNotifyRequest.ClientOptionsEntryR\rClientOptions\x1a_\n" +
	"\x12ClientOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.nodepb.ClientDeliveryOptionsR\x05value:\x028\x01*\xc7\x01\n" +
	"\x18ClientDeliveryNotifyKind\x12+\n" +
	"'CLIENT_DELIVERY_NOTIFY_KIND_UNSPECIFIED\x10\x00\x12$\n" +
	" CLIENT_DELIVERY_NOTIFY_KIND_WAKE\x10\x01\x12+\n" +
	"'CLIENT_DELIVERY_NOTIFY_KIND_QOS0_DIRECT\x10\x02\x12+\n" +
	"'CLIENT_DELIVERY_NOTIFY_KIND_SHARED_WAKE\x10\x032]\n" +
	"\x14ClientDeliveryNotify\x12E\n" +
	"\x06Notify\x12#.nodepb.ClientDeliveryNotifyRequest\x1a\x16.google.protobuf.EmptyB9Z7github.com/BAN1ce/skyTree/pkg/broker/grpc/nodepb;nodepbb\x06proto3"

var (
	file_notify_client_delivery_proto_rawDescOnce sync.Once
	file_notify_client_delivery_proto_rawDescData []byte
)

func file_notify_client_delivery_proto_rawDescGZIP() []byte {
	file_notify_client_delivery_proto_rawDescOnce.Do(func() {
		file_notify_client_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notify_client_delivery_proto_rawDesc), len(file_notify_client_delivery_proto_rawDesc)))
	})
	return file_notify_client_delivery_proto_rawDescData
}

var file_notify_client_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notify_client_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notify_client_delivery_proto_goTypes = []any{
	(ClientDeliveryNotifyKind)(0),       // 0: nodepb.ClientDeliveryNotifyKind
	(*ClientDeliveryOptions)(nil),       // 1: nodepb.ClientDeliveryOptions
	(*ClientDeliveryNotifyRequest)(nil), // 2: nodepb.ClientDeliveryNotifyRequest
	nil,                                 // 3: nodepb.ClientDeliveryNotifyRequest.ClientOptionsEntry
	(*emptypb.Empty)(nil),               // 4: google.protobuf.Empty
}
var file_notify_client_delivery_proto_depIdxs = []int32{
	0, // 0: nodepb.ClientDeliveryNotifyRequest.Kind:type_name -> nodepb.ClientDeliveryNotifyKind
	3, // 1: nodepb.ClientDeliveryNotifyRequest.ClientOptions:type_name -> nodepb.ClientDeliveryNotifyRequest.ClientOptionsEntry
	1, // 2: nodepb.ClientDeliveryNotifyRequest.ClientOptionsEntry.value:type_name -> nodepb.ClientDeliveryOptions
	2, // 3: nodepb.ClientDeliveryNotify.Notify:input_type -> nodepb.ClientDeliveryNotifyRequest
	4, // 4: nodepb.ClientDeliveryNotify.Notify:output_type -> google.protobuf.Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notify_client_delivery_proto_init() }
func file_notify_client_delivery_proto_init() {
	if File_notify_client_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_client_delivery_proto_rawDesc), len(file_notify_client_delivery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_client_delivery_proto_goTypes,
		DependencyIndexes: file_notify_client_delivery_proto_depIdxs,
		EnumInfos:         file_notify_client_delivery_proto_enumTypes,
		MessageInfos:      file_notify_client_delivery_proto_msgTypes,
	}.Build()
	File_notify_client_delivery_proto = out.File
	file_notify_client_delivery_proto_goTypes = nil
	file_notify_client_delivery_proto_depIdxs = nil
}
