run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - funlen
    - gocyclo

linters-settings:
  funlen:
    lines: 180
    statements: 90
  gocyclo:
    min-complexity: 25

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
