// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/proto_session/session.proto

package proto_session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionRequestType int32

const (
	SessionRequestType_OPEN_SESSION_FOR_CONNECT             SessionRequestType = 0
	SessionRequestType_TAKE_OVER_SESSION_OWNER              SessionRequestType = 1
	SessionRequestType_REPLACE_SESSION_STATE_ON_CLEAN_START SessionRequestType = 2
	SessionRequestType_SAVE_OFFLINE_STATE                   SessionRequestType = 3
	SessionRequestType_DELETE_SESSION                       SessionRequestType = 4
	SessionRequestType_REMOVE_OUTGOING_UNFINISHED           SessionRequestType = 5
	SessionRequestType_DELETE_EXPIRED_SESSIONS              SessionRequestType = 6
	SessionRequestType_UPSERT_INCOMING_UNFINISHED           SessionRequestType = 7
	SessionRequestType_REMOVE_INCOMING_UNFINISHED           SessionRequestType = 8
	// Periodic in-flight commit of downlink delivery progress while the client is online.
	// Unlike SAVE_OFFLINE_STATE it must not change owner online state or the offline expiry.
	SessionRequestType_COMMIT_OUTGOING_PROGRESS SessionRequestType = 9
)

// Enum value maps for SessionRequestType.
var (
	SessionRequestType_name = map[int32]string{
		0: "OPEN_SESSION_FOR_CONNECT",
		1: "TAKE_OVER_SESSION_OWNER",
		2: "REPLACE_SESSION_STATE_ON_CLEAN_START",
		3: "SAVE_OFFLINE_STATE",
		4: "DELETE_SESSION",
		5: "REMOVE_OUTGOING_UNFINISHED",
		6: "DELETE_EXPIRED_SESSIONS",
		7: "UPSERT_INCOMING_UNFINISHED",
		8: "REMOVE_INCOMING_UNFINISHED",
		9: "COMMIT_OUTGOING_PROGRESS",
	}
	SessionRequestType_value = map[string]int32{
		"OPEN_SESSION_FOR_CONNECT":             0,
		"TAKE_OVER_SESSION_OWNER":              1,
		"REPLACE_SESSION_STATE_ON_CLEAN_START": 2,
		"SAVE_OFFLINE_STATE":                   3,
		"DELETE_SESSION":                       4,
		"REMOVE_OUTGOING_UNFINISHED":           5,
		"DELETE_EXPIRED_SESSIONS":              6,
		"UPSERT_INCOMING_UNFINISHED":           7,
		"REMOVE_INCOMING_UNFINISHED":           8,
		"COMMIT_OUTGOING_PROGRESS":             9,
	}
)

func (x SessionRequestType) Enum() *SessionRequestType {
	p := new(SessionRequestType)
	*p = x
	return p
}

func (x SessionRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_session_session_proto_enumTypes[0].Descriptor()
}

func (SessionRequestType) Type() protoreflect.EnumType {
	return &file_proto_proto_session_session_proto_enumTypes[0]
}

func (x SessionRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionRequestType.Descriptor instead.
func (SessionRequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{0}
}

// Message state for QoS flow
type UnfinishedMessage_MessageState int32

const (
	// For QoS1: waiting for PUBACK
	UnfinishedMessage_WAITING_PUBACK UnfinishedMessage_MessageState = 0
	// For QoS2: waiting for PUBREC
	UnfinishedMessage_WAITING_PUBREC UnfinishedMessage_MessageState = 1
	// For QoS2: received PUBREC, waiting for PUBCOMP (outgoing)
	UnfinishedMessage_WAITING_PUBCOMP UnfinishedMessage_MessageState = 2
	// For QoS2: received PUBLISH, waiting for PUBREL (incoming)
	UnfinishedMessage_WAITING_PUBREL UnfinishedMessage_MessageState = 3
)

// Enum value maps for UnfinishedMessage_MessageState.
var (
	UnfinishedMessage_MessageState_name = map[int32]string{
		0: "WAITING_PUBACK",
		1: "WAITING_PUBREC",
		2: "WAITING_PUBCOMP",
		3: "WAITING_PUBREL",
	}
	UnfinishedMessage_MessageState_value = map[string]int32{
		"WAITING_PUBACK":  0,
		"WAITING_PUBREC":  1,
		"WAITING_PUBCOMP": 2,
		"WAITING_PUBREL":  3,
	}
)

func (x UnfinishedMessage_MessageState) Enum() *UnfinishedMessage_MessageState {
	p := new(UnfinishedMessage_MessageState)
	*p = x
	return p
}

func (x UnfinishedMessage_MessageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnfinishedMessage_MessageState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_session_session_proto_enumTypes[1].Descriptor()
}

func (UnfinishedMessage_MessageState) Type() protoreflect.EnumType {
	return &file_proto_proto_session_session_proto_enumTypes[1]
}

func (x UnfinishedMessage_MessageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnfinishedMessage_MessageState.Descriptor instead.
func (UnfinishedMessage_MessageState) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{2, 0}
}

// UserProperty 表示用户属性键值对（支持重复键）
type UserProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProperty) Reset() {
	*x = UserProperty{}
	mi := &file_proto_proto_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProperty) ProtoMessage() {}

func (x *UserProperty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProperty.ProtoReflect.Descriptor instead.
func (*UserProperty) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *UserProperty) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserProperty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// WillMessage 表示遗嘱消息
type WillMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 遗嘱主题
	Topic string `protobuf:"bytes,1,opt,name=Topic,json=topic,proto3" json:"Topic,omitempty"`
	// 遗嘱消息内容
	Payload []byte `protobuf:"bytes,2,opt,name=Payload,json=payload,proto3" json:"Payload,omitempty"`
	// QoS
	Qos uint32 `protobuf:"varint,3,opt,name=Qos,json=qos,proto3" json:"Qos,omitempty"`
	// 保留标志
	Retain bool `protobuf:"varint,4,opt,name=Retain,json=retain,proto3" json:"Retain,omitempty"`
	// MQTT 5.0 遗嘱属性（已废弃，保留用于向后兼容）
	//
	// Deprecated: Marked as deprecated in proto/proto_session/session.proto.
	Properties map[string]string `protobuf:"bytes,5,rep,name=Properties,json=properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Content Type
	ContentType *string `protobuf:"bytes,6,opt,name=ContentType,json=content_type,proto3,oneof" json:"ContentType,omitempty"`
	// Response Topic
	ResponseTopic *string `protobuf:"bytes,7,opt,name=ResponseTopic,json=response_topic,proto3,oneof" json:"ResponseTopic,omitempty"`
	// Correlation Data
	CorrelationData []byte `protobuf:"bytes,8,opt,name=CorrelationData,json=correlation_data,proto3,oneof" json:"CorrelationData,omitempty"`
	// Message Expiry Interval (seconds)
	MessageExpiry *uint32 `protobuf:"varint,9,opt,name=MessageExpiry,json=message_expiry,proto3,oneof" json:"MessageExpiry,omitempty"`
	// User Properties (支持重复键)
	UserProperties []*UserProperty `protobuf:"bytes,10,rep,name=UserProperties,json=user_properties,proto3" json:"UserProperties,omitempty"`
	// Payload Format Indicator
	PayloadFormat *uint32 `protobuf:"varint,11,opt,name=PayloadFormat,json=payload_format,proto3,oneof" json:"PayloadFormat,omitempty"`
	// Will Delay Interval (seconds)
	WillDelayInterval *uint32 `protobuf:"varint,12,opt,name=WillDelayInterval,json=will_delay_interval,proto3,oneof" json:"WillDelayInterval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WillMessage) Reset() {
	*x = WillMessage{}
	mi := &file_proto_proto_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WillMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WillMessage) ProtoMessage() {}

func (x *WillMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WillMessage.ProtoReflect.Descriptor instead.
func (*WillMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *WillMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *WillMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WillMessage) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *WillMessage) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

// Deprecated: Marked as deprecated in proto/proto_session/session.proto.
func (x *WillMessage) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *WillMessage) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *WillMessage) GetResponseTopic() string {
	if x != nil && x.ResponseTopic != nil {
		return *x.ResponseTopic
	}
	return ""
}

func (x *WillMessage) GetCorrelationData() []byte {
	if x != nil {
		return x.CorrelationData
	}
	return nil
}

func (x *WillMessage) GetMessageExpiry() uint32 {
	if x != nil && x.MessageExpiry != nil {
		return *x.MessageExpiry
	}
	return 0
}

func (x *WillMessage) GetUserProperties() []*UserProperty {
	if x != nil {
		return x.UserProperties
	}
	return nil
}

func (x *WillMessage) GetPayloadFormat() uint32 {
	if x != nil && x.PayloadFormat != nil {
		return *x.PayloadFormat
	}
	return 0
}

func (x *WillMessage) GetWillDelayInterval() uint32 {
	if x != nil && x.WillDelayInterval != nil {
		return *x.WillDelayInterval
	}
	return 0
}

// UnfinishedMessage 表示未完成的 QoS1/QoS2 消息
type UnfinishedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message UUID (from message store)
	MessageID string `protobuf:"bytes,1,opt,name=MessageID,json=message_id,proto3" json:"MessageID,omitempty"`
	// MQTT Packet ID
	PacketID uint32 `protobuf:"varint,2,opt,name=PacketID,json=packet_id,proto3" json:"PacketID,omitempty"`
	// QoS level (1 or 2)
	Qos uint32 `protobuf:"varint,3,opt,name=Qos,json=qos,proto3" json:"Qos,omitempty"`
	// Current message state
	State UnfinishedMessage_MessageState `protobuf:"varint,4,opt,name=State,json=state,proto3,enum=session.UnfinishedMessage_MessageState" json:"State,omitempty"`
	// Subscribe topic (for outgoing messages)
	SubscribeTopic *string `protobuf:"bytes,5,opt,name=SubscribeTopic,json=subscribe_topic,proto3,oneof" json:"SubscribeTopic,omitempty"`
	// Direction: true for outgoing (broker to client), false for incoming (client to broker)
	IsOutgoing bool `protobuf:"varint,6,opt,name=IsOutgoing,json=is_outgoing,proto3" json:"IsOutgoing,omitempty"`
	// First publish timestamp (Unix microseconds)
	FirstPubTime int64 `protobuf:"varint,7,opt,name=FirstPubTime,json=first_pub_time,proto3" json:"FirstPubTime,omitempty"`
	// Encoded MQTT PUBLISH control packet for incoming QoS2 messages waiting for PUBREL.
	PublishPacket []byte `protobuf:"bytes,8,opt,name=PublishPacket,json=publish_packet,proto3" json:"PublishPacket,omitempty"`
	// PUBREC reason code already sent for incoming QoS2 messages waiting for PUBREL.
	AckReasonCode uint32 `protobuf:"varint,9,opt,name=AckReasonCode,json=ack_reason_code,proto3" json:"AckReasonCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfinishedMessage) Reset() {
	*x = UnfinishedMessage{}
	mi := &file_proto_proto_session_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfinishedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfinishedMessage) ProtoMessage() {}

func (x *UnfinishedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfinishedMessage.ProtoReflect.Descriptor instead.
func (*UnfinishedMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{2}
}

func (x *UnfinishedMessage) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *UnfinishedMessage) GetPacketID() uint32 {
	if x != nil {
		return x.PacketID
	}
	return 0
}

func (x *UnfinishedMessage) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *UnfinishedMessage) GetState() UnfinishedMessage_MessageState {
	if x != nil {
		return x.State
	}
	return UnfinishedMessage_WAITING_PUBACK
}

func (x *UnfinishedMessage) GetSubscribeTopic() string {
	if x != nil && x.SubscribeTopic != nil {
		return *x.SubscribeTopic
	}
	return ""
}

func (x *UnfinishedMessage) GetIsOutgoing() bool {
	if x != nil {
		return x.IsOutgoing
	}
	return false
}

func (x *UnfinishedMessage) GetFirstPubTime() int64 {
	if x != nil {
		return x.FirstPubTime
	}
	return 0
}

func (x *UnfinishedMessage) GetPublishPacket() []byte {
	if x != nil {
		return x.PublishPacket
	}
	return nil
}

func (x *UnfinishedMessage) GetAckReasonCode() uint32 {
	if x != nil {
		return x.AckReasonCode
	}
	return 0
}

// OutgoingReplayCursor records the earliest downlink QoS1 delivery task that
// must be replayed after reconnect. QoS1 does not need per-packet protocol
// state because duplicate PUBLISH delivery is allowed by at-least-once
// semantics.
type OutgoingReplayCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUnixMicro int64                  `protobuf:"varint,1,opt,name=TaskUnixMicro,json=task_unix_micro,proto3" json:"TaskUnixMicro,omitempty"`
	TaskID        string                 `protobuf:"bytes,2,opt,name=TaskID,json=task_id,proto3" json:"TaskID,omitempty"`
	Generation    int64                  `protobuf:"varint,3,opt,name=Generation,json=generation,proto3" json:"Generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingReplayCursor) Reset() {
	*x = OutgoingReplayCursor{}
	mi := &file_proto_proto_session_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingReplayCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingReplayCursor) ProtoMessage() {}

func (x *OutgoingReplayCursor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingReplayCursor.ProtoReflect.Descriptor instead.
func (*OutgoingReplayCursor) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{3}
}

func (x *OutgoingReplayCursor) GetTaskUnixMicro() int64 {
	if x != nil {
		return x.TaskUnixMicro
	}
	return 0
}

func (x *OutgoingReplayCursor) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *OutgoingReplayCursor) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// Session 表示一个客户端会话，包含客户端信息和会话数据
type Session struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientID string                 `protobuf:"bytes,1,opt,name=ClientID,json=client_id,proto3" json:"ClientID,omitempty"`
	// 遗嘱消息
	WillMessage *WillMessage `protobuf:"bytes,2,opt,name=WillMessage,json=will_message,proto3,oneof" json:"WillMessage,omitempty"`
	// Unfinished QoS2 and retained outgoing messages that require exact protocol restoration.
	UnfinishedMessages []*UnfinishedMessage `protobuf:"bytes,3,rep,name=UnfinishedMessages,json=unfinished_messages,proto3" json:"UnfinishedMessages,omitempty"`
	// MQTT 5.0 Session Expiry Interval (seconds)
	SessionExpiryInterval uint32 `protobuf:"varint,4,opt,name=SessionExpiryInterval,json=session_expiry_interval,proto3" json:"SessionExpiryInterval,omitempty"`
	// Offline expiry deadline. 0 means the session is online or never expires.
	ExpireAtUnixNano int64 `protobuf:"varint,5,opt,name=ExpireAtUnixNano,json=expire_at_unix_nano,proto3" json:"ExpireAtUnixNano,omitempty"`
	// Earliest ordinary outgoing QoS1 delivery task to replay.
	OutgoingReplayCursor *OutgoingReplayCursor `protobuf:"bytes,6,opt,name=OutgoingReplayCursor,json=outgoing_replay_cursor,proto3,oneof" json:"OutgoingReplayCursor,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_proto_session_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Session) GetWillMessage() *WillMessage {
	if x != nil {
		return x.WillMessage
	}
	return nil
}

func (x *Session) GetUnfinishedMessages() []*UnfinishedMessage {
	if x != nil {
		return x.UnfinishedMessages
	}
	return nil
}

func (x *Session) GetSessionExpiryInterval() uint32 {
	if x != nil {
		return x.SessionExpiryInterval
	}
	return 0
}

func (x *Session) GetExpireAtUnixNano() int64 {
	if x != nil {
		return x.ExpireAtUnixNano
	}
	return 0
}

func (x *Session) GetOutgoingReplayCursor() *OutgoingReplayCursor {
	if x != nil {
		return x.OutgoingReplayCursor
	}
	return nil
}

// SessionOwner 表示运行时 ownership / 路由状态。
// 注意：它不是 MQTT session 语义的一部分，只是当前实现中用于显式隔离 runtime 状态。
type SessionOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,json=client_id,proto3" json:"ClientID,omitempty"`
	NodeID        uint64                 `protobuf:"varint,2,opt,name=NodeID,json=node_id,proto3" json:"NodeID,omitempty"`
	OwnerToken    string                 `protobuf:"bytes,3,opt,name=OwnerToken,json=owner_token,proto3" json:"OwnerToken,omitempty"`
	Online        bool                   `protobuf:"varint,4,opt,name=Online,json=online,proto3" json:"Online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOwner) Reset() {
	*x = SessionOwner{}
	mi := &file_proto_proto_session_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOwner) ProtoMessage() {}

func (x *SessionOwner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOwner.ProtoReflect.Descriptor instead.
func (*SessionOwner) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{5}
}

func (x *SessionOwner) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *SessionOwner) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *SessionOwner) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

func (x *SessionOwner) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// ClusterSessions 表示集群中的所有会话
type ClusterSessions struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Sessions      map[string]*Session      `protobuf:"bytes,1,rep,name=Sessions,proto3" json:"Sessions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Owners        map[string]*SessionOwner `protobuf:"bytes,2,rep,name=Owners,proto3" json:"Owners,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSessions) Reset() {
	*x = ClusterSessions{}
	mi := &file_proto_proto_session_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSessions) ProtoMessage() {}

func (x *ClusterSessions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSessions.ProtoReflect.Descriptor instead.
func (*ClusterSessions) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterSessions) GetSessions() map[string]*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ClusterSessions) GetOwners() map[string]*SessionOwner {
	if x != nil {
		return x.Owners
	}
	return nil
}

// SessionRequest 通用会话请求
type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	Type          SessionRequestType     `protobuf:"varint,2,opt,name=Type,proto3,enum=session.SessionRequestType" json:"Type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Time          int64                  `protobuf:"varint,4,opt,name=Time,proto3" json:"Time,omitempty"`
	ClientID      string                 `protobuf:"bytes,5,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RequestNodeID uint64                 `protobuf:"varint,6,opt,name=RequestNodeID,proto3" json:"RequestNodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{7}
}

func (x *SessionRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *SessionRequest) GetType() SessionRequestType {
	if x != nil {
		return x.Type
	}
	return SessionRequestType_OPEN_SESSION_FOR_CONNECT
}

func (x *SessionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SessionRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SessionRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *SessionRequest) GetRequestNodeID() uint64 {
	if x != nil {
		return x.RequestNodeID
	}
	return 0
}

type OpenSessionForConnectRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientID              string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	WillMessage           *WillMessage           `protobuf:"bytes,2,opt,name=WillMessage,json=will_message,proto3,oneof" json:"WillMessage,omitempty"`
	SessionExpiryInterval uint32                 `protobuf:"varint,3,opt,name=SessionExpiryInterval,json=session_expiry_interval,proto3" json:"SessionExpiryInterval,omitempty"`
	NowUnixNano           int64                  `protobuf:"varint,4,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OpenSessionForConnectRequest) Reset() {
	*x = OpenSessionForConnectRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionForConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionForConnectRequest) ProtoMessage() {}

func (x *OpenSessionForConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionForConnectRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionForConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{8}
}

func (x *OpenSessionForConnectRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *OpenSessionForConnectRequest) GetWillMessage() *WillMessage {
	if x != nil {
		return x.WillMessage
	}
	return nil
}

func (x *OpenSessionForConnectRequest) GetSessionExpiryInterval() uint32 {
	if x != nil {
		return x.SessionExpiryInterval
	}
	return 0
}

func (x *OpenSessionForConnectRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

type OpenSessionForConnectResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OldSession       *Session               `protobuf:"bytes,1,opt,name=OldSession,proto3" json:"OldSession,omitempty"`
	OldSessionExists bool                   `protobuf:"varint,2,opt,name=OldSessionExists,proto3" json:"OldSessionExists,omitempty"`
	Session          *Session               `protobuf:"bytes,3,opt,name=Session,proto3" json:"Session,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenSessionForConnectResponse) Reset() {
	*x = OpenSessionForConnectResponse{}
	mi := &file_proto_proto_session_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionForConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionForConnectResponse) ProtoMessage() {}

func (x *OpenSessionForConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionForConnectResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionForConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{9}
}

func (x *OpenSessionForConnectResponse) GetOldSession() *Session {
	if x != nil {
		return x.OldSession
	}
	return nil
}

func (x *OpenSessionForConnectResponse) GetOldSessionExists() bool {
	if x != nil {
		return x.OldSessionExists
	}
	return false
}

func (x *OpenSessionForConnectResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type TakeOverSessionOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *SessionOwner          `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeOverSessionOwnerRequest) Reset() {
	*x = TakeOverSessionOwnerRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOverSessionOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverSessionOwnerRequest) ProtoMessage() {}

func (x *TakeOverSessionOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverSessionOwnerRequest.ProtoReflect.Descriptor instead.
func (*TakeOverSessionOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{10}
}

func (x *TakeOverSessionOwnerRequest) GetOwner() *SessionOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

type TakeOverSessionOwnerResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PreviousOwner       *SessionOwner          `protobuf:"bytes,1,opt,name=PreviousOwner,proto3" json:"PreviousOwner,omitempty"`
	PreviousOwnerExists bool                   `protobuf:"varint,2,opt,name=PreviousOwnerExists,proto3" json:"PreviousOwnerExists,omitempty"`
	Owner               *SessionOwner          `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TakeOverSessionOwnerResponse) Reset() {
	*x = TakeOverSessionOwnerResponse{}
	mi := &file_proto_proto_session_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOverSessionOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverSessionOwnerResponse) ProtoMessage() {}

func (x *TakeOverSessionOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverSessionOwnerResponse.ProtoReflect.Descriptor instead.
func (*TakeOverSessionOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{11}
}

func (x *TakeOverSessionOwnerResponse) GetPreviousOwner() *SessionOwner {
	if x != nil {
		return x.PreviousOwner
	}
	return nil
}

func (x *TakeOverSessionOwnerResponse) GetPreviousOwnerExists() bool {
	if x != nil {
		return x.PreviousOwnerExists
	}
	return false
}

func (x *TakeOverSessionOwnerResponse) GetOwner() *SessionOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

type ReplaceSessionStateOnCleanStartRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientID              string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	WillMessage           *WillMessage           `protobuf:"bytes,2,opt,name=WillMessage,json=will_message,proto3,oneof" json:"WillMessage,omitempty"`
	SessionExpiryInterval uint32                 `protobuf:"varint,3,opt,name=SessionExpiryInterval,json=session_expiry_interval,proto3" json:"SessionExpiryInterval,omitempty"`
	NowUnixNano           int64                  `protobuf:"varint,4,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReplaceSessionStateOnCleanStartRequest) Reset() {
	*x = ReplaceSessionStateOnCleanStartRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceSessionStateOnCleanStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceSessionStateOnCleanStartRequest) ProtoMessage() {}

func (x *ReplaceSessionStateOnCleanStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceSessionStateOnCleanStartRequest.ProtoReflect.Descriptor instead.
func (*ReplaceSessionStateOnCleanStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{12}
}

func (x *ReplaceSessionStateOnCleanStartRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ReplaceSessionStateOnCleanStartRequest) GetWillMessage() *WillMessage {
	if x != nil {
		return x.WillMessage
	}
	return nil
}

func (x *ReplaceSessionStateOnCleanStartRequest) GetSessionExpiryInterval() uint32 {
	if x != nil {
		return x.SessionExpiryInterval
	}
	return 0
}

func (x *ReplaceSessionStateOnCleanStartRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSessionRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type DeleteExpiredSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NowUnixNano   int64                  `protobuf:"varint,1,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpiredSessionsRequest) Reset() {
	*x = DeleteExpiredSessionsRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpiredSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpiredSessionsRequest) ProtoMessage() {}

func (x *DeleteExpiredSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpiredSessionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpiredSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteExpiredSessionsRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

type DeleteExpiredSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIDs     []string               `protobuf:"bytes,1,rep,name=ClientIDs,json=client_ids,proto3" json:"ClientIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpiredSessionsResponse) Reset() {
	*x = DeleteExpiredSessionsResponse{}
	mi := &file_proto_proto_session_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpiredSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpiredSessionsResponse) ProtoMessage() {}

func (x *DeleteExpiredSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpiredSessionsResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpiredSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteExpiredSessionsResponse) GetClientIDs() []string {
	if x != nil {
		return x.ClientIDs
	}
	return nil
}

type SaveOfflineStateRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientID              string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	UnfinishedMessages    []*UnfinishedMessage   `protobuf:"bytes,2,rep,name=UnfinishedMessages,json=unfinished_messages,proto3" json:"UnfinishedMessages,omitempty"`
	WillMessage           *WillMessage           `protobuf:"bytes,3,opt,name=WillMessage,json=will_message,proto3,oneof" json:"WillMessage,omitempty"`
	ClearWill             bool                   `protobuf:"varint,4,opt,name=ClearWill,json=clear_will,proto3" json:"ClearWill,omitempty"`
	SessionExpiryInterval uint32                 `protobuf:"varint,5,opt,name=SessionExpiryInterval,json=session_expiry_interval,proto3" json:"SessionExpiryInterval,omitempty"`
	NowUnixNano           int64                  `protobuf:"varint,6,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	OwnerToken            string                 `protobuf:"bytes,7,opt,name=OwnerToken,json=owner_token,proto3" json:"OwnerToken,omitempty"`
	OutgoingReplayCursor  *OutgoingReplayCursor  `protobuf:"bytes,8,opt,name=OutgoingReplayCursor,json=outgoing_replay_cursor,proto3,oneof" json:"OutgoingReplayCursor,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SaveOfflineStateRequest) Reset() {
	*x = SaveOfflineStateRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveOfflineStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOfflineStateRequest) ProtoMessage() {}

func (x *SaveOfflineStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOfflineStateRequest.ProtoReflect.Descriptor instead.
func (*SaveOfflineStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{16}
}

func (x *SaveOfflineStateRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *SaveOfflineStateRequest) GetUnfinishedMessages() []*UnfinishedMessage {
	if x != nil {
		return x.UnfinishedMessages
	}
	return nil
}

func (x *SaveOfflineStateRequest) GetWillMessage() *WillMessage {
	if x != nil {
		return x.WillMessage
	}
	return nil
}

func (x *SaveOfflineStateRequest) GetClearWill() bool {
	if x != nil {
		return x.ClearWill
	}
	return false
}

func (x *SaveOfflineStateRequest) GetSessionExpiryInterval() uint32 {
	if x != nil {
		return x.SessionExpiryInterval
	}
	return 0
}

func (x *SaveOfflineStateRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

func (x *SaveOfflineStateRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

func (x *SaveOfflineStateRequest) GetOutgoingReplayCursor() *OutgoingReplayCursor {
	if x != nil {
		return x.OutgoingReplayCursor
	}
	return nil
}

type RemoveOutgoingUnfinishedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	MessageID     string                 `protobuf:"bytes,2,opt,name=MessageID,json=message_id,proto3" json:"MessageID,omitempty"`
	NowUnixNano   int64                  `protobuf:"varint,3,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOutgoingUnfinishedRequest) Reset() {
	*x = RemoveOutgoingUnfinishedRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOutgoingUnfinishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOutgoingUnfinishedRequest) ProtoMessage() {}

func (x *RemoveOutgoingUnfinishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOutgoingUnfinishedRequest.ProtoReflect.Descriptor instead.
func (*RemoveOutgoingUnfinishedRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveOutgoingUnfinishedRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *RemoveOutgoingUnfinishedRequest) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *RemoveOutgoingUnfinishedRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

type UpsertIncomingUnfinishedRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientID          string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PacketID          uint32                 `protobuf:"varint,2,opt,name=PacketID,json=packet_id,proto3" json:"PacketID,omitempty"`
	UnfinishedMessage *UnfinishedMessage     `protobuf:"bytes,3,opt,name=UnfinishedMessage,json=unfinished_message,proto3" json:"UnfinishedMessage,omitempty"`
	OwnerToken        string                 `protobuf:"bytes,4,opt,name=OwnerToken,json=owner_token,proto3" json:"OwnerToken,omitempty"`
	NowUnixNano       int64                  `protobuf:"varint,5,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertIncomingUnfinishedRequest) Reset() {
	*x = UpsertIncomingUnfinishedRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertIncomingUnfinishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertIncomingUnfinishedRequest) ProtoMessage() {}

func (x *UpsertIncomingUnfinishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertIncomingUnfinishedRequest.ProtoReflect.Descriptor instead.
func (*UpsertIncomingUnfinishedRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{18}
}

func (x *UpsertIncomingUnfinishedRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *UpsertIncomingUnfinishedRequest) GetPacketID() uint32 {
	if x != nil {
		return x.PacketID
	}
	return 0
}

func (x *UpsertIncomingUnfinishedRequest) GetUnfinishedMessage() *UnfinishedMessage {
	if x != nil {
		return x.UnfinishedMessage
	}
	return nil
}

func (x *UpsertIncomingUnfinishedRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

func (x *UpsertIncomingUnfinishedRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

type RemoveIncomingUnfinishedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PacketID      uint32                 `protobuf:"varint,2,opt,name=PacketID,json=packet_id,proto3" json:"PacketID,omitempty"`
	OwnerToken    string                 `protobuf:"bytes,3,opt,name=OwnerToken,json=owner_token,proto3" json:"OwnerToken,omitempty"`
	NowUnixNano   int64                  `protobuf:"varint,4,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIncomingUnfinishedRequest) Reset() {
	*x = RemoveIncomingUnfinishedRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIncomingUnfinishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIncomingUnfinishedRequest) ProtoMessage() {}

func (x *RemoveIncomingUnfinishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIncomingUnfinishedRequest.ProtoReflect.Descriptor instead.
func (*RemoveIncomingUnfinishedRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveIncomingUnfinishedRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *RemoveIncomingUnfinishedRequest) GetPacketID() uint32 {
	if x != nil {
		return x.PacketID
	}
	return 0
}

func (x *RemoveIncomingUnfinishedRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

func (x *RemoveIncomingUnfinishedRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

// CommitOutgoingProgressRequest carries a compact snapshot of downlink delivery progress,
// committed periodically while the client is online so an unexpected crash does not force a
// full replay. It replaces only the outgoing portion of the session state:
//   - OutgoingReplayCursor: earliest unacked ordinary QoS1 delivery task (position replay).
//   - UnfinishedMessages: current in-flight QoS2/retained outgoing entries (stage-accurate
//     restore via PacketID + state). Bounded by the downlink Receive Maximum window.
//
// It must not touch the will, session expiry, incoming unfinished messages, or owner online state.
type CommitOutgoingProgressRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientID             string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	UnfinishedMessages   []*UnfinishedMessage   `protobuf:"bytes,2,rep,name=UnfinishedMessages,json=unfinished_messages,proto3" json:"UnfinishedMessages,omitempty"`
	OutgoingReplayCursor *OutgoingReplayCursor  `protobuf:"bytes,3,opt,name=OutgoingReplayCursor,json=outgoing_replay_cursor,proto3,oneof" json:"OutgoingReplayCursor,omitempty"`
	OwnerToken           string                 `protobuf:"bytes,4,opt,name=OwnerToken,json=owner_token,proto3" json:"OwnerToken,omitempty"`
	NowUnixNano          int64                  `protobuf:"varint,5,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CommitOutgoingProgressRequest) Reset() {
	*x = CommitOutgoingProgressRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOutgoingProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOutgoingProgressRequest) ProtoMessage() {}

func (x *CommitOutgoingProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOutgoingProgressRequest.ProtoReflect.Descriptor instead.
func (*CommitOutgoingProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{20}
}

func (x *CommitOutgoingProgressRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *CommitOutgoingProgressRequest) GetUnfinishedMessages() []*UnfinishedMessage {
	if x != nil {
		return x.UnfinishedMessages
	}
	return nil
}

func (x *CommitOutgoingProgressRequest) GetOutgoingReplayCursor() *OutgoingReplayCursor {
	if x != nil {
		return x.OutgoingReplayCursor
	}
	return nil
}

func (x *CommitOutgoingProgressRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

func (x *CommitOutgoingProgressRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

type ReadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	NowUnixNano   int64                  `protobuf:"varint,2,opt,name=NowUnixNano,json=now_unix_nano,proto3" json:"NowUnixNano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionRequest) Reset() {
	*x = ReadSessionRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionRequest) ProtoMessage() {}

func (x *ReadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionRequest.ProtoReflect.Descriptor instead.
func (*ReadSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{21}
}

func (x *ReadSessionRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ReadSessionRequest) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

type ReadSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=Session,json=session,proto3" json:"Session,omitempty"`
	Exist         bool                   `protobuf:"varint,2,opt,name=Exist,json=exist,proto3" json:"Exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionResponse) Reset() {
	*x = ReadSessionResponse{}
	mi := &file_proto_proto_session_session_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionResponse) ProtoMessage() {}

func (x *ReadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionResponse.ProtoReflect.Descriptor instead.
func (*ReadSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{22}
}

func (x *ReadSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ReadSessionResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type ReadSessionOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionOwnerRequest) Reset() {
	*x = ReadSessionOwnerRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionOwnerRequest) ProtoMessage() {}

func (x *ReadSessionOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionOwnerRequest.ProtoReflect.Descriptor instead.
func (*ReadSessionOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{23}
}

func (x *ReadSessionOwnerRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type ReadSessionOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *SessionOwner          `protobuf:"bytes,1,opt,name=Owner,json=owner,proto3" json:"Owner,omitempty"`
	Exist         bool                   `protobuf:"varint,2,opt,name=Exist,json=exist,proto3" json:"Exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionOwnerResponse) Reset() {
	*x = ReadSessionOwnerResponse{}
	mi := &file_proto_proto_session_session_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionOwnerResponse) ProtoMessage() {}

func (x *ReadSessionOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionOwnerResponse.ProtoReflect.Descriptor instead.
func (*ReadSessionOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{24}
}

func (x *ReadSessionOwnerResponse) GetOwner() *SessionOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ReadSessionOwnerResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type ReadSessionOwnersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIDs     []string               `protobuf:"bytes,1,rep,name=ClientIDs,json=client_ids,proto3" json:"ClientIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionOwnersRequest) Reset() {
	*x = ReadSessionOwnersRequest{}
	mi := &file_proto_proto_session_session_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionOwnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionOwnersRequest) ProtoMessage() {}

func (x *ReadSessionOwnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionOwnersRequest.ProtoReflect.Descriptor instead.
func (*ReadSessionOwnersRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{25}
}

func (x *ReadSessionOwnersRequest) GetClientIDs() []string {
	if x != nil {
		return x.ClientIDs
	}
	return nil
}

type ReadSessionOwnerItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,json=client_id,proto3" json:"ClientID,omitempty"`
	Owner         *SessionOwner          `protobuf:"bytes,2,opt,name=Owner,json=owner,proto3" json:"Owner,omitempty"`
	Exist         bool                   `protobuf:"varint,3,opt,name=Exist,json=exist,proto3" json:"Exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionOwnerItem) Reset() {
	*x = ReadSessionOwnerItem{}
	mi := &file_proto_proto_session_session_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionOwnerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionOwnerItem) ProtoMessage() {}

func (x *ReadSessionOwnerItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionOwnerItem.ProtoReflect.Descriptor instead.
func (*ReadSessionOwnerItem) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{26}
}

func (x *ReadSessionOwnerItem) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ReadSessionOwnerItem) GetOwner() *SessionOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ReadSessionOwnerItem) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type ReadSessionOwnersResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*ReadSessionOwnerItem `protobuf:"bytes,1,rep,name=Items,json=items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionOwnersResponse) Reset() {
	*x = ReadSessionOwnersResponse{}
	mi := &file_proto_proto_session_session_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionOwnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionOwnersResponse) ProtoMessage() {}

func (x *ReadSessionOwnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_session_session_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionOwnersResponse.ProtoReflect.Descriptor instead.
func (*ReadSessionOwnersResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_session_session_proto_rawDescGZIP(), []int{27}
}

func (x *ReadSessionOwnersResponse) GetItems() []*ReadSessionOwnerItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_proto_session_session_proto protoreflect.FileDescriptor

const file_proto_proto_session_session_proto_rawDesc = "" +
	"\n" +
	"!proto/proto_session/session.proto\x12\asession\"6\n" +
	"\fUserProperty\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05value\"\xb1\x05\n" +
	"\vWillMessage\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\aPayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03Qos\x18\x03 \x01(\rR\x03qos\x12\x16\n" +
	"\x06Retain\x18\x04 \x01(\bR\x06retain\x12H\n" +
	"\n" +
	"Properties\x18\x05 \x03(\v2$.session.WillMessage.PropertiesEntryB\x02\x18\x01R\n" +
	"properties\x12&\n" +
	"\vContentType\x18\x06 \x01(\tH\x00R\fcontent_type\x88\x01\x01\x12*\n" +
	"\rResponseTopic\x18\a \x01(\tH\x01R\x0eresponse_topic\x88\x01\x01\x12.\n" +
	"\x0fCorrelationData\x18\b \x01(\fH\x02R\x10correlation_data\x88\x01\x01\x12*\n" +
	"\rMessageExpiry\x18\t \x01(\rH\x03R\x0emessage_expiry\x88\x01\x01\x12>\n" +
	"\x0eUserProperties\x18\n" +
	" \x03(\v2\x15.session.UserPropertyR\x0fuser_properties\x12*\n" +
	"\rPayloadFormat\x18\v \x01(\rH\x04R\x0epayload_format\x88\x01\x01\x123\n" +
	"\x11WillDelayInterval\x18\f \x01(\rH\x05R\x13will_delay_interval\x88\x01\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_ContentTypeB\x10\n" +
	"\x0e_ResponseTopicB\x12\n" +
	"\x10_CorrelationDataB\x10\n" +
	"\x0e_MessageExpiryB\x10\n" +
	"\x0e_PayloadFormatB\x14\n" +
	"\x12_WillDelayInterval\"\xd8\x03\n" +
	"\x11UnfinishedMessage\x12\x1d\n" +
	"\tMessageID\x18\x01 \x01(\tR\n" +
	"message_id\x12\x1b\n" +
	"\bPacketID\x18\x02 \x01(\rR\tpacket_id\x12\x10\n" +
	"\x03Qos\x18\x03 \x01(\rR\x03qos\x12=\n" +
	"\x05State\x18\x04 \x01(\x0e2'.session.UnfinishedMessage.MessageStateR\x05state\x12,\n" +
	"\x0eSubscribeTopic\x18\x05 \x01(\tH\x00R\x0fsubscribe_topic\x88\x01\x01\x12\x1f\n" +
	"\n" +
	"IsOutgoing\x18\x06 \x01(\bR\vis_outgoing\x12$\n" +
	"\fFirstPubTime\x18\a \x01(\x03R\x0efirst_pub_time\x12%\n" +
	"\rPublishPacket\x18\b \x01(\fR\x0epublish_packet\x12&\n" +
	"\rAckReasonCode\x18\t \x01(\rR\x0fack_reason_code\"_\n" +
	"\fMessageState\x12\x12\n" +
	"\x0eWAITING_PUBACK\x10\x00\x12\x12\n" +
	"\x0eWAITING_PUBREC\x10\x01\x12\x13\n" +
	"\x0fWAITING_PUBCOMP\x10\x02\x12\x12\n" +
	"\x0eWAITING_PUBREL\x10\x03B\x11\n" +
	"\x0f_SubscribeTopic\"w\n" +
	"\x14OutgoingReplayCursor\x12&\n" +
	"\rTaskUnixMicro\x18\x01 \x01(\x03R\x0ftask_unix_micro\x12\x17\n" +
	"\x06TaskID\x18\x02 \x01(\tR\atask_id\x12\x1e\n" +
	"\n" +
	"Generation\x18\x03 \x01(\x03R\n" +
	"generation\"\x9b\x03\n" +
	"\aSession\x12\x1b\n" +
	"\bClientID\x18\x01 \x01(\tR\tclient_id\x12<\n" +
	"\vWillMessage\x18\x02 \x01(\v2\x14.session.WillMessageH\x00R\fwill_message\x88\x01\x01\x12K\n" +
	"\x12UnfinishedMessages\x18\x03 \x03(\v2\x1a.session.UnfinishedMessageR\x13unfinished_messages\x126\n" +
	"\x15SessionExpiryInterval\x18\x04 \x01(\rR\x17session_expiry_interval\x12-\n" +
	"\x10ExpireAtUnixNano\x18\x05 \x01(\x03R\x13expire_at_unix_nano\x12X\n" +
	"\x14OutgoingReplayCursor\x18\x06 \x01(\v2\x1d.session.OutgoingReplayCursorH\x01R\x16outgoing_replay_cursor\x88\x01\x01B\x0e\n" +
	"\f_WillMessageB\x17\n" +
	"\x15_OutgoingReplayCursor\"}\n" +
	"\fSessionOwner\x12\x1b\n" +
	"\bClientID\x18\x01 \x01(\tR\tclient_id\x12\x17\n" +
	"\x06NodeID\x18\x02 \x01(\x04R\anode_id\x12\x1f\n" +
	"\n" +
	"OwnerToken\x18\x03 \x01(\tR\vowner_token\x12\x16\n" +
	"\x06Online\x18\x04 \x01(\bR\x06online\"\xb4\x02\n" +
	"\x0fClusterSessions\x12B\n" +
	"\bSessions\x18\x01 \x03(\v2&.session.ClusterSessions.SessionsEntryR\bSessions\x12<\n" +
	"\x06Owners\x18\x02 \x03(\v2$.session.ClusterSessions.OwnersEntryR\x06Owners\x1aM\n" +
	"\rSessionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.session.SessionR\x05value:\x028\x01\x1aP\n" +
	"\vOwnersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.session.SessionOwnerR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x0eSessionRequest\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12/\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x1b.session.SessionRequestTypeR\x04Type\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x12\n" +
	"\x04Time\x18\x04 \x01(\x03R\x04Time\x12\x1a\n" +
	"\bClientID\x18\x05 \x01(\tR\bClientID\x12$\n" +
	"\rRequestNodeID\x18\x06 \x01(\x04R\rRequestNodeID\"\xe4\x01\n" +
	"\x1cOpenSessionForConnectRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12<\n" +
	"\vWillMessage\x18\x02 \x01(\v2\x14.session.WillMessageH\x00R\fwill_message\x88\x01\x01\x126\n" +
	"\x15SessionExpiryInterval\x18\x03 \x01(\rR\x17session_expiry_interval\x12\"\n" +
	"\vNowUnixNano\x18\x04 \x01(\x03R\rnow_unix_nanoB\x0e\n" +
	"\f_WillMessage\"\xa9\x01\n" +
	"\x1dOpenSessionForConnectResponse\x120\n" +
	"\n" +
	"OldSession\x18\x01 \x01(\v2\x10.session.SessionR\n" +
	"OldSession\x12*\n" +
	"\x10OldSessionExists\x18\x02 \x01(\bR\x10OldSessionExists\x12*\n" +
	"\aSession\x18\x03 \x01(\v2\x10.session.SessionR\aSession\"J\n" +
	"\x1bTakeOverSessionOwnerRequest\x12+\n" +
	"\x05Owner\x18\x01 \x01(\v2\x15.session.SessionOwnerR\x05Owner\"\xba\x01\n" +
	"\x1cTakeOverSessionOwnerResponse\x12;\n" +
	"\rPreviousOwner\x18\x01 \x01(\v2\x15.session.SessionOwnerR\rPreviousOwner\x120\n" +
	"\x13PreviousOwnerExists\x18\x02 \x01(\bR\x13PreviousOwnerExists\x12+\n" +
	"\x05Owner\x18\x03 \x01(\v2\x15.session.SessionOwnerR\x05Owner\"\xee\x01\n" +
	"&ReplaceSessionStateOnCleanStartRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12<\n" +
	"\vWillMessage\x18\x02 \x01(\v2\x14.session.WillMessageH\x00R\fwill_message\x88\x01\x01\x126\n" +
	"\x15SessionExpiryInterval\x18\x03 \x01(\rR\x17session_expiry_interval\x12\"\n" +
	"\vNowUnixNano\x18\x04 \x01(\x03R\rnow_unix_nanoB\x0e\n" +
	"\f_WillMessage\"2\n" +
	"\x14DeleteSessionRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\"B\n" +
	"\x1cDeleteExpiredSessionsRequest\x12\"\n" +
	"\vNowUnixNano\x18\x01 \x01(\x03R\rnow_unix_nano\">\n" +
	"\x1dDeleteExpiredSessionsResponse\x12\x1d\n" +
	"\tClientIDs\x18\x01 \x03(\tR\n" +
	"client_ids\"\xdf\x03\n" +
	"\x17SaveOfflineStateRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12K\n" +
	"\x12UnfinishedMessages\x18\x02 \x03(\v2\x1a.session.UnfinishedMessageR\x13unfinished_messages\x12<\n" +
	"\vWillMessage\x18\x03 \x01(\v2\x14.session.WillMessageH\x00R\fwill_message\x88\x01\x01\x12\x1d\n" +
	"\tClearWill\x18\x04 \x01(\bR\n" +
	"clear_will\x126\n" +
	"\x15SessionExpiryInterval\x18\x05 \x01(\rR\x17session_expiry_interval\x12\"\n" +
	"\vNowUnixNano\x18\x06 \x01(\x03R\rnow_unix_nano\x12\x1f\n" +
	"\n" +
	"OwnerToken\x18\a \x01(\tR\vowner_token\x12X\n" +
	"\x14OutgoingReplayCursor\x18\b \x01(\v2\x1d.session.OutgoingReplayCursorH\x01R\x16outgoing_replay_cursor\x88\x01\x01B\x0e\n" +
	"\f_WillMessageB\x17\n" +
	"\x15_OutgoingReplayCursor\"\x80\x01\n" +
	"\x1fRemoveOutgoingUnfinishedRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\x1d\n" +
	"\tMessageID\x18\x02 \x01(\tR\n" +
	"message_id\x12\"\n" +
	"\vNowUnixNano\x18\x03 \x01(\x03R\rnow_unix_nano\"\xea\x01\n" +
	"\x1fUpsertIncomingUnfinishedRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\x1b\n" +
	"\bPacketID\x18\x02 \x01(\rR\tpacket_id\x12I\n" +
	"\x11UnfinishedMessage\x18\x03 \x01(\v2\x1a.session.UnfinishedMessageR\x12unfinished_message\x12\x1f\n" +
	"\n" +
	"OwnerToken\x18\x04 \x01(\tR\vowner_token\x12\"\n" +
	"\vNowUnixNano\x18\x05 \x01(\x03R\rnow_unix_nano\"\x9f\x01\n" +
	"\x1fRemoveIncomingUnfinishedRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\x1b\n" +
	"\bPacketID\x18\x02 \x01(\rR\tpacket_id\x12\x1f\n" +
	"\n" +
	"OwnerToken\x18\x03 \x01(\tR\vowner_token\x12\"\n" +
	"\vNowUnixNano\x18\x04 \x01(\x03R\rnow_unix_nano\"\xc0\x02\n" +
	"\x1dCommitOutgoingProgressRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12K\n" +
	"\x12UnfinishedMessages\x18\x02 \x03(\v2\x1a.session.UnfinishedMessageR\x13unfinished_messages\x12X\n" +
	"\x14OutgoingReplayCursor\x18\x03 \x01(\v2\x1d.session.OutgoingReplayCursorH\x00R\x16outgoing_replay_cursor\x88\x01\x01\x12\x1f\n" +
	"\n" +
	"OwnerToken\x18\x04 \x01(\tR\vowner_token\x12\"\n" +
	"\vNowUnixNano\x18\x05 \x01(\x03R\rnow_unix_nanoB\x17\n" +
	"\x15_OutgoingReplayCursor\"T\n" +
	"\x12ReadSessionRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\"\n" +
	"\vNowUnixNano\x18\x02 \x01(\x03R\rnow_unix_nano\"W\n" +
	"\x13ReadSessionResponse\x12*\n" +
	"\aSession\x18\x01 \x01(\v2\x10.session.SessionR\asession\x12\x14\n" +
	"\x05Exist\x18\x02 \x01(\bR\x05exist\"5\n" +
	"\x17ReadSessionOwnerRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\"]\n" +
	"\x18ReadSessionOwnerResponse\x12+\n" +
	"\x05Owner\x18\x01 \x01(\v2\x15.session.SessionOwnerR\x05owner\x12\x14\n" +
	"\x05Exist\x18\x02 \x01(\bR\x05exist\"9\n" +
	"\x18ReadSessionOwnersRequest\x12\x1d\n" +
	"\tClientIDs\x18\x01 \x03(\tR\n" +
	"client_ids\"v\n" +
	"\x14ReadSessionOwnerItem\x12\x1b\n" +
	"\bClientID\x18\x01 \x01(\tR\tclient_id\x12+\n" +
	"\x05Owner\x18\x02 \x01(\v2\x15.session.SessionOwnerR\x05owner\x12\x14\n" +
	"\x05Exist\x18\x03 \x01(\bR\x05exist\"P\n" +
	"\x19ReadSessionOwnersResponse\x123\n" +
	"\x05Items\x18\x01 \x03(\v2\x1d.session.ReadSessionOwnerItemR\x05items*\xc0\x02\n" +
	"\x12SessionRequestType\x12\x1c\n" +
	"\x18OPEN_SESSION_FOR_CONNECT\x10\x00\x12\x1b\n" +
	"\x17TAKE_OVER_SESSION_OWNER\x10\x01\x12(\n" +
	"$REPLACE_SESSION_STATE_ON_CLEAN_START\x10\x02\x12\x16\n" +
	"\x12SAVE_OFFLINE_STATE\x10\x03\x12\x12\n" +
	"\x0eDELETE_SESSION\x10\x04\x12\x1e\n" +
	"\x1aREMOVE_OUTGOING_UNFINISHED\x10\x05\x12\x1b\n" +
	"\x17DELETE_EXPIRED_SESSIONS\x10\x06\x12\x1e\n" +
	"\x1aUPSERT_INCOMING_UNFINISHED\x10\a\x12\x1e\n" +
	"\x1aREMOVE_INCOMING_UNFINISHED\x10\b\x12\x1c\n" +
	"\x18COMMIT_OUTGOING_PROGRESS\x10\tB\x12Z\x10./;proto_sessionb\x06proto3"

var (
	file_proto_proto_session_session_proto_rawDescOnce sync.Once
	file_proto_proto_session_session_proto_rawDescData []byte
)

func file_proto_proto_session_session_proto_rawDescGZIP() []byte {
	file_proto_proto_session_session_proto_rawDescOnce.Do(func() {
		file_proto_proto_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_session_session_proto_rawDesc), len(file_proto_proto_session_session_proto_rawDesc)))
	})
	return file_proto_proto_session_session_proto_rawDescData
}

var file_proto_proto_session_session_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_proto_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_proto_session_session_proto_goTypes = []any{
	(SessionRequestType)(0),                        // 0: session.SessionRequestType
	(UnfinishedMessage_MessageState)(0),            // 1: session.UnfinishedMessage.MessageState
	(*UserProperty)(nil),                           // 2: session.UserProperty
	(*WillMessage)(nil),                            // 3: session.WillMessage
	(*UnfinishedMessage)(nil),                      // 4: session.UnfinishedMessage
	(*OutgoingReplayCursor)(nil),                   // 5: session.OutgoingReplayCursor
	(*Session)(nil),                                // 6: session.Session
	(*SessionOwner)(nil),                           // 7: session.SessionOwner
	(*ClusterSessions)(nil),                        // 8: session.ClusterSessions
	(*SessionRequest)(nil),                         // 9: session.SessionRequest
	(*OpenSessionForConnectRequest)(nil),           // 10: session.OpenSessionForConnectRequest
	(*OpenSessionForConnectResponse)(nil),          // 11: session.OpenSessionForConnectResponse
	(*TakeOverSessionOwnerRequest)(nil),            // 12: session.TakeOverSessionOwnerRequest
	(*TakeOverSessionOwnerResponse)(nil),           // 13: session.TakeOverSessionOwnerResponse
	(*ReplaceSessionStateOnCleanStartRequest)(nil), // 14: session.ReplaceSessionStateOnCleanStartRequest
	(*DeleteSessionRequest)(nil),                   // 15: session.DeleteSessionRequest
	(*DeleteExpiredSessionsRequest)(nil),           // 16: session.DeleteExpiredSessionsRequest
	(*DeleteExpiredSessionsResponse)(nil),          // 17: session.DeleteExpiredSessionsResponse
	(*SaveOfflineStateRequest)(nil),                // 18: session.SaveOfflineStateRequest
	(*RemoveOutgoingUnfinishedRequest)(nil),        // 19: session.RemoveOutgoingUnfinishedRequest
	(*UpsertIncomingUnfinishedRequest)(nil),        // 20: session.UpsertIncomingUnfinishedRequest
	(*RemoveIncomingUnfinishedRequest)(nil),        // 21: session.RemoveIncomingUnfinishedRequest
	(*CommitOutgoingProgressRequest)(nil),          // 22: session.CommitOutgoingProgressRequest
	(*ReadSessionRequest)(nil),                     // 23: session.ReadSessionRequest
	(*ReadSessionResponse)(nil),                    // 24: session.ReadSessionResponse
	(*ReadSessionOwnerRequest)(nil),                // 25: session.ReadSessionOwnerRequest
	(*ReadSessionOwnerResponse)(nil),               // 26: session.ReadSessionOwnerResponse
	(*ReadSessionOwnersRequest)(nil),               // 27: session.ReadSessionOwnersRequest
	(*ReadSessionOwnerItem)(nil),                   // 28: session.ReadSessionOwnerItem
	(*ReadSessionOwnersResponse)(nil),              // 29: session.ReadSessionOwnersResponse
	nil,                                            // 30: session.WillMessage.PropertiesEntry
	nil,                                            // 31: session.ClusterSessions.SessionsEntry
	nil,                                            // 32: session.ClusterSessions.OwnersEntry
}
var file_proto_proto_session_session_proto_depIdxs = []int32{
	30, // 0: session.WillMessage.Properties:type_name -> session.WillMessage.PropertiesEntry
	2,  // 1: session.WillMessage.UserProperties:type_name -> session.UserProperty
	1,  // 2: session.UnfinishedMessage.State:type_name -> session.UnfinishedMessage.MessageState
	3,  // 3: session.Session.WillMessage:type_name -> session.WillMessage
	4,  // 4: session.Session.UnfinishedMessages:type_name -> session.UnfinishedMessage
	5,  // 5: session.Session.OutgoingReplayCursor:type_name -> session.OutgoingReplayCursor
	31, // 6: session.ClusterSessions.Sessions:type_name -> session.ClusterSessions.SessionsEntry
	32, // 7: session.ClusterSessions.Owners:type_name -> session.ClusterSessions.OwnersEntry
	0,  // 8: session.SessionRequest.Type:type_name -> session.SessionRequestType
	3,  // 9: session.OpenSessionForConnectRequest.WillMessage:type_name -> session.WillMessage
	6,  // 10: session.OpenSessionForConnectResponse.OldSession:type_name -> session.Session
	6,  // 11: session.OpenSessionForConnectResponse.Session:type_name -> session.Session
	7,  // 12: session.TakeOverSessionOwnerRequest.Owner:type_name -> session.SessionOwner
	7,  // 13: session.TakeOverSessionOwnerResponse.PreviousOwner:type_name -> session.SessionOwner
	7,  // 14: session.TakeOverSessionOwnerResponse.Owner:type_name -> session.SessionOwner
	3,  // 15: session.ReplaceSessionStateOnCleanStartRequest.WillMessage:type_name -> session.WillMessage
	4,  // 16: session.SaveOfflineStateRequest.UnfinishedMessages:type_name -> session.UnfinishedMessage
	3,  // 17: session.SaveOfflineStateRequest.WillMessage:type_name -> session.WillMessage
	5,  // 18: session.SaveOfflineStateRequest.OutgoingReplayCursor:type_name -> session.OutgoingReplayCursor
	4,  // 19: session.UpsertIncomingUnfinishedRequest.UnfinishedMessage:type_name -> session.UnfinishedMessage
	4,  // 20: session.CommitOutgoingProgressRequest.UnfinishedMessages:type_name -> session.UnfinishedMessage
	5,  // 21: session.CommitOutgoingProgressRequest.OutgoingReplayCursor:type_name -> session.OutgoingReplayCursor
	6,  // 22: session.ReadSessionResponse.Session:type_name -> session.Session
	7,  // 23: session.ReadSessionOwnerResponse.Owner:type_name -> session.SessionOwner
	7,  // 24: session.ReadSessionOwnerItem.Owner:type_name -> session.SessionOwner
	28, // 25: session.ReadSessionOwnersResponse.Items:type_name -> session.ReadSessionOwnerItem
	6,  // 26: session.ClusterSessions.SessionsEntry.value:type_name -> session.Session
	7,  // 27: session.ClusterSessions.OwnersEntry.value:type_name -> session.SessionOwner
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_proto_session_session_proto_init() }
func file_proto_proto_session_session_proto_init() {
	if File_proto_proto_session_session_proto != nil {
		return
	}
	file_proto_proto_session_session_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_proto_session_session_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_proto_session_session_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_proto_session_session_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_proto_session_session_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_proto_session_session_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_proto_session_session_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_session_session_proto_rawDesc), len(file_proto_proto_session_session_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_session_session_proto_goTypes,
		DependencyIndexes: file_proto_proto_session_session_proto_depIdxs,
		EnumInfos:         file_proto_proto_session_session_proto_enumTypes,
		MessageInfos:      file_proto_proto_session_session_proto_msgTypes,
	}.Build()
	File_proto_proto_session_session_proto = out.File
	file_proto_proto_session_session_proto_goTypes = nil
	file_proto_proto_session_session_proto_depIdxs = nil
}
