// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/proto_topic/topic.proto

package proto_topic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicRequestType int32

const (
	TopicRequestType_Sub          TopicRequestType = 0
	TopicRequestType_UnSub        TopicRequestType = 1
	TopicRequestType_DeleteClient TopicRequestType = 2
	TopicRequestType_DeleteTopic  TopicRequestType = 3
	// SetClientOwnerToken updates the current ownership fencing token for a client.
	TopicRequestType_SetClientOwnerToken TopicRequestType = 4
)

// Enum value maps for TopicRequestType.
var (
	TopicRequestType_name = map[int32]string{
		0: "Sub",
		1: "UnSub",
		2: "DeleteClient",
		3: "DeleteTopic",
		4: "SetClientOwnerToken",
	}
	TopicRequestType_value = map[string]int32{
		"Sub":                 0,
		"UnSub":               1,
		"DeleteClient":        2,
		"DeleteTopic":         3,
		"SetClientOwnerToken": 4,
	}
)

func (x TopicRequestType) Enum() *TopicRequestType {
	p := new(TopicRequestType)
	*p = x
	return p
}

func (x TopicRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopicRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_topic_topic_proto_enumTypes[0].Descriptor()
}

func (TopicRequestType) Type() protoreflect.EnumType {
	return &file_proto_proto_topic_topic_proto_enumTypes[0]
}

func (x TopicRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopicRequestType.Descriptor instead.
func (TopicRequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{0}
}

type SubOption struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QoS               int32                  `protobuf:"varint,1,opt,name=QoS,proto3" json:"QoS,omitempty"`
	RetainAsPublished bool                   `protobuf:"varint,2,opt,name=RetainAsPublished,proto3" json:"RetainAsPublished,omitempty"`
	Topic             string                 `protobuf:"bytes,3,opt,name=Topic,proto3" json:"Topic,omitempty"`
	// MQTT5 subscription options and metadata.
	NoLocal        bool  `protobuf:"varint,4,opt,name=NoLocal,proto3" json:"NoLocal,omitempty"`
	RetainHandling int32 `protobuf:"varint,5,opt,name=RetainHandling,proto3" json:"RetainHandling,omitempty"`
	// SubscriptionIdentifier is the MQTT5 Subscription Identifier attached to this subscription (SUBSCRIBE property).
	// 0 means not set.
	SubscriptionIdentifier int32 `protobuf:"varint,6,opt,name=SubscriptionIdentifier,proto3" json:"SubscriptionIdentifier,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SubOption) Reset() {
	*x = SubOption{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubOption) ProtoMessage() {}

func (x *SubOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubOption.ProtoReflect.Descriptor instead.
func (*SubOption) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{0}
}

func (x *SubOption) GetQoS() int32 {
	if x != nil {
		return x.QoS
	}
	return 0
}

func (x *SubOption) GetRetainAsPublished() bool {
	if x != nil {
		return x.RetainAsPublished
	}
	return false
}

func (x *SubOption) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubOption) GetNoLocal() bool {
	if x != nil {
		return x.NoLocal
	}
	return false
}

func (x *SubOption) GetRetainHandling() int32 {
	if x != nil {
		return x.RetainHandling
	}
	return 0
}

func (x *SubOption) GetSubscriptionIdentifier() int32 {
	if x != nil {
		return x.SubscriptionIdentifier
	}
	return 0
}

type TopicClientsID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       map[string]*SubOption  `protobuf:"bytes,1,rep,name=Clients,proto3" json:"Clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is clientID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicClientsID) Reset() {
	*x = TopicClientsID{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicClientsID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicClientsID) ProtoMessage() {}

func (x *TopicClientsID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicClientsID.ProtoReflect.Descriptor instead.
func (*TopicClientsID) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{1}
}

func (x *TopicClientsID) GetClients() map[string]*SubOption {
	if x != nil {
		return x.Clients
	}
	return nil
}

type TopicSubTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeRoot      *TreeNode              `protobuf:"bytes,1,opt,name=TreeRoot,proto3" json:"TreeRoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicSubTree) Reset() {
	*x = TopicSubTree{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicSubTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSubTree) ProtoMessage() {}

func (x *TopicSubTree) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSubTree.ProtoReflect.Descriptor instead.
func (*TopicSubTree) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{2}
}

func (x *TopicSubTree) GetTreeRoot() *TreeNode {
	if x != nil {
		return x.TreeRoot
	}
	return nil
}

type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicSection  string                 `protobuf:"bytes,1,opt,name=TopicSection,proto3" json:"TopicSection,omitempty"`                                                                     // topic section
	Topic         string                 `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`                                                                                   // full topic
	Client        map[string]*SubOption  `protobuf:"bytes,3,rep,name=Client,proto3" json:"Client,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // sub clients, key is clientID
	ChildNode     map[string]*TreeNode   `protobuf:"bytes,4,rep,name=ChildNode,proto3" json:"ChildNode,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // child tree
	ClusterSub    map[string]int64       `protobuf:"bytes,5,rep,name=ClusterSub,proto3" json:"ClusterSub,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{3}
}

func (x *TreeNode) GetTopicSection() string {
	if x != nil {
		return x.TopicSection
	}
	return ""
}

func (x *TreeNode) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TreeNode) GetClient() map[string]*SubOption {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *TreeNode) GetChildNode() map[string]*TreeNode {
	if x != nil {
		return x.ChildNode
	}
	return nil
}

func (x *TreeNode) GetClusterSub() map[string]int64 {
	if x != nil {
		return x.ClusterSub
	}
	return nil
}

type ClientSubTopic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        map[string]*SubOption  `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is topic
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSubTopic) Reset() {
	*x = ClientSubTopic{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSubTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSubTopic) ProtoMessage() {}

func (x *ClientSubTopic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSubTopic.ProtoReflect.Descriptor instead.
func (*ClientSubTopic) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{4}
}

func (x *ClientSubTopic) GetTopics() map[string]*SubOption {
	if x != nil {
		return x.Topics
	}
	return nil
}

type ClientManager struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Clients       map[string]*ClientSubTopic `protobuf:"bytes,1,rep,name=Clients,proto3" json:"Clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is clientID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientManager) Reset() {
	*x = ClientManager{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientManager) ProtoMessage() {}

func (x *ClientManager) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientManager.ProtoReflect.Descriptor instead.
func (*ClientManager) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{5}
}

func (x *ClientManager) GetClients() map[string]*ClientSubTopic {
	if x != nil {
		return x.Clients
	}
	return nil
}

type SubCore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *TopicSubTree          `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Clients       *ClientManager         `protobuf:"bytes,2,opt,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCore) Reset() {
	*x = SubCore{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCore) ProtoMessage() {}

func (x *SubCore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCore.ProtoReflect.Descriptor instead.
func (*SubCore) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{6}
}

func (x *SubCore) GetRoot() *TopicSubTree {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *SubCore) GetClients() *ClientManager {
	if x != nil {
		return x.Clients
	}
	return nil
}

type ClusterSub struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Cluster map[string]*SubCore    `protobuf:"bytes,1,rep,name=cluster,proto3" json:"cluster,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ClientOwnerTokens is used for snapshotting the current fencing token for each client.
	ClientOwnerTokens map[string]string `protobuf:"bytes,2,rep,name=ClientOwnerTokens,proto3" json:"ClientOwnerTokens,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClusterSub) Reset() {
	*x = ClusterSub{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSub) ProtoMessage() {}

func (x *ClusterSub) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSub.ProtoReflect.Descriptor instead.
func (*ClusterSub) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterSub) GetCluster() map[string]*SubCore {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *ClusterSub) GetClientOwnerTokens() map[string]string {
	if x != nil {
		return x.ClientOwnerTokens
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TopicRequestType       `protobuf:"varint,1,opt,name=Type,proto3,enum=proto.TopicRequestType" json:"Type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	RequestID     string                 `protobuf:"bytes,3,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequest) GetType() TopicRequestType {
	if x != nil {
		return x.Type
	}
	return TopicRequestType_Sub
}

func (x *UpdateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TopicRequestType       `protobuf:"varint,1,opt,name=Type,proto3,enum=proto.TopicRequestType" json:"Type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	RequestID     string                 `protobuf:"bytes,3,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateResponse) GetType() TopicRequestType {
	if x != nil {
		return x.Type
	}
	return TopicRequestType_Sub
}

func (x *UpdateResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type SubRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Topics   []*SubOption           `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	ClientID string                 `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	// OwnerToken is a fencing token (UUID string) for this client connection.
	OwnerToken    string `protobuf:"bytes,3,opt,name=OwnerToken,proto3" json:"OwnerToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{10}
}

func (x *SubRequest) GetTopics() []*SubOption {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *SubRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *SubRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

type SubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        map[string]int32       `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Success       bool                   `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubResponse) Reset() {
	*x = SubResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubResponse) ProtoMessage() {}

func (x *SubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubResponse.ProtoReflect.Descriptor instead.
func (*SubResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{11}
}

func (x *SubResponse) GetTopics() map[string]int32 {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *SubResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnSubRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Topics     []string               `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	ClientID   string                 `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Share      bool                   `protobuf:"varint,3,opt,name=Share,proto3" json:"Share,omitempty"`
	ShareGroup string                 `protobuf:"bytes,4,opt,name=ShareGroup,proto3" json:"ShareGroup,omitempty"`
	// OwnerToken is a fencing token (UUID string) for this client connection.
	OwnerToken    string `protobuf:"bytes,5,opt,name=OwnerToken,proto3" json:"OwnerToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnSubRequest) Reset() {
	*x = UnSubRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnSubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSubRequest) ProtoMessage() {}

func (x *UnSubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSubRequest.ProtoReflect.Descriptor instead.
func (*UnSubRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{12}
}

func (x *UnSubRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *UnSubRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *UnSubRequest) GetShare() bool {
	if x != nil {
		return x.Share
	}
	return false
}

func (x *UnSubRequest) GetShareGroup() string {
	if x != nil {
		return x.ShareGroup
	}
	return ""
}

func (x *UnSubRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

type UnSubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []int32                `protobuf:"varint,1,rep,packed,name=Topics,proto3" json:"Topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnSubResponse) Reset() {
	*x = UnSubResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnSubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSubResponse) ProtoMessage() {}

func (x *UnSubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSubResponse.ProtoReflect.Descriptor instead.
func (*UnSubResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{13}
}

func (x *UnSubResponse) GetTopics() []int32 {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetAllMatchTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMatchTopicsRequest) Reset() {
	*x = GetAllMatchTopicsRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMatchTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMatchTopicsRequest) ProtoMessage() {}

func (x *GetAllMatchTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMatchTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetAllMatchTopicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllMatchTopicsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetAllMatchTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         map[string]int32       `protobuf:"bytes,2,rep,name=Topic,proto3" json:"Topic,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMatchTopicsResponse) Reset() {
	*x = GetAllMatchTopicsResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMatchTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMatchTopicsResponse) ProtoMessage() {}

func (x *GetAllMatchTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMatchTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetAllMatchTopicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllMatchTopicsResponse) GetTopic() map[string]int32 {
	if x != nil {
		return x.Topic
	}
	return nil
}

type GetAllMatchTopicsForWildTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMatchTopicsForWildTopicRequest) Reset() {
	*x = GetAllMatchTopicsForWildTopicRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMatchTopicsForWildTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMatchTopicsForWildTopicRequest) ProtoMessage() {}

func (x *GetAllMatchTopicsForWildTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMatchTopicsForWildTopicRequest.ProtoReflect.Descriptor instead.
func (*GetAllMatchTopicsForWildTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllMatchTopicsForWildTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetAllMatchTopicsForWildTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         []string               `protobuf:"bytes,1,rep,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMatchTopicsForWildTopicResponse) Reset() {
	*x = GetAllMatchTopicsForWildTopicResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMatchTopicsForWildTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMatchTopicsForWildTopicResponse) ProtoMessage() {}

func (x *GetAllMatchTopicsForWildTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMatchTopicsForWildTopicResponse.ProtoReflect.Descriptor instead.
func (*GetAllMatchTopicsForWildTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllMatchTopicsForWildTopicResponse) GetTopic() []string {
	if x != nil {
		return x.Topic
	}
	return nil
}

type GetAllSubTopicClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubTopicClientRequest) Reset() {
	*x = GetAllSubTopicClientRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubTopicClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubTopicClientRequest) ProtoMessage() {}

func (x *GetAllSubTopicClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubTopicClientRequest.ProtoReflect.Descriptor instead.
func (*GetAllSubTopicClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllSubTopicClientRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetAllSubTopicClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        map[string]*SubOption  `protobuf:"bytes,1,rep,name=Client,proto3" json:"Client,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is clientID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubTopicClientResponse) Reset() {
	*x = GetAllSubTopicClientResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubTopicClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubTopicClientResponse) ProtoMessage() {}

func (x *GetAllSubTopicClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubTopicClientResponse.ProtoReflect.Descriptor instead.
func (*GetAllSubTopicClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{19}
}

func (x *GetAllSubTopicClientResponse) GetClient() map[string]*SubOption {
	if x != nil {
		return x.Client
	}
	return nil
}

type GetAllMatchClientV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMatchClientV2Request) Reset() {
	*x = GetAllMatchClientV2Request{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMatchClientV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMatchClientV2Request) ProtoMessage() {}

func (x *GetAllMatchClientV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMatchClientV2Request.ProtoReflect.Descriptor instead.
func (*GetAllMatchClientV2Request) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{20}
}

func (x *GetAllMatchClientV2Request) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type MatchedSubscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TopicFilter is the subscription filter that matched (may contain wildcards).
	TopicFilter            string `protobuf:"bytes,1,opt,name=TopicFilter,proto3" json:"TopicFilter,omitempty"`
	QoS                    int32  `protobuf:"varint,2,opt,name=QoS,proto3" json:"QoS,omitempty"`
	RetainAsPublished      bool   `protobuf:"varint,3,opt,name=RetainAsPublished,proto3" json:"RetainAsPublished,omitempty"`
	NoLocal                bool   `protobuf:"varint,4,opt,name=NoLocal,proto3" json:"NoLocal,omitempty"`
	RetainHandling         int32  `protobuf:"varint,5,opt,name=RetainHandling,proto3" json:"RetainHandling,omitempty"`
	SubscriptionIdentifier int32  `protobuf:"varint,6,opt,name=SubscriptionIdentifier,proto3" json:"SubscriptionIdentifier,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MatchedSubscription) Reset() {
	*x = MatchedSubscription{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedSubscription) ProtoMessage() {}

func (x *MatchedSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedSubscription.ProtoReflect.Descriptor instead.
func (*MatchedSubscription) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{21}
}

func (x *MatchedSubscription) GetTopicFilter() string {
	if x != nil {
		return x.TopicFilter
	}
	return ""
}

func (x *MatchedSubscription) GetQoS() int32 {
	if x != nil {
		return x.QoS
	}
	return 0
}

func (x *MatchedSubscription) GetRetainAsPublished() bool {
	if x != nil {
		return x.RetainAsPublished
	}
	return false
}

func (x *MatchedSubscription) GetNoLocal() bool {
	if x != nil {
		return x.NoLocal
	}
	return false
}

func (x *MatchedSubscription) GetRetainHandling() int32 {
	if x != nil {
		return x.RetainHandling
	}
	return 0
}

func (x *MatchedSubscription) GetSubscriptionIdentifier() int32 {
	if x != nil {
		return x.SubscriptionIdentifier
	}
	return 0
}

type ClientMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	MaxQoS        int32                  `protobuf:"varint,2,opt,name=MaxQoS,proto3" json:"MaxQoS,omitempty"`
	Matched       []*MatchedSubscription `protobuf:"bytes,3,rep,name=Matched,proto3" json:"Matched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMatch) Reset() {
	*x = ClientMatch{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMatch) ProtoMessage() {}

func (x *ClientMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMatch.ProtoReflect.Descriptor instead.
func (*ClientMatch) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{22}
}

func (x *ClientMatch) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ClientMatch) GetMaxQoS() int32 {
	if x != nil {
		return x.MaxQoS
	}
	return 0
}

func (x *ClientMatch) GetMatched() []*MatchedSubscription {
	if x != nil {
		return x.Matched
	}
	return nil
}

type GetAllMatchClientV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*ClientMatch         `protobuf:"bytes,1,rep,name=Matches,proto3" json:"Matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMatchClientV2Response) Reset() {
	*x = GetAllMatchClientV2Response{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMatchClientV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMatchClientV2Response) ProtoMessage() {}

func (x *GetAllMatchClientV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMatchClientV2Response.ProtoReflect.Descriptor instead.
func (*GetAllMatchClientV2Response) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{23}
}

func (x *GetAllMatchClientV2Response) GetMatches() []*ClientMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GetSubTreeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic is the subtree root topic. When empty, it means the virtual root "/" (show all).
	Topic string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	// MaxDepth limits the returned subtree depth (0 means no children, 1 means one level, etc).
	// When MaxDepth <= 0, the server will use an internal default.
	MaxDepth      int32 `protobuf:"varint,2,opt,name=MaxDepth,proto3" json:"MaxDepth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubTreeRequest) Reset() {
	*x = GetSubTreeRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubTreeRequest) ProtoMessage() {}

func (x *GetSubTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubTreeRequest.ProtoReflect.Descriptor instead.
func (*GetSubTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{24}
}

func (x *GetSubTreeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetSubTreeRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type GetSubTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *TreeNode              `protobuf:"bytes,1,opt,name=Root,proto3" json:"Root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubTreeResponse) Reset() {
	*x = GetSubTreeResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubTreeResponse) ProtoMessage() {}

func (x *GetSubTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubTreeResponse.ProtoReflect.Descriptor instead.
func (*GetSubTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{25}
}

func (x *GetSubTreeResponse) GetRoot() *TreeNode {
	if x != nil {
		return x.Root
	}
	return nil
}

type DeleteClientRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientID string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Topic    []string               `protobuf:"bytes,2,rep,name=Topic,proto3" json:"Topic,omitempty"`
	// OwnerToken is optional. When present, the server will only delete subscriptions
	// if the stored owner token for this client matches (fencing). When empty, treat as force-delete.
	OwnerToken    string `protobuf:"bytes,3,opt,name=OwnerToken,proto3" json:"OwnerToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteClientRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *DeleteClientRequest) GetTopic() []string {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *DeleteClientRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

// SetClientOwnerTokenRequest sets/overwrites the fencing token for a client.
type SetClientOwnerTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	OwnerToken    string                 `protobuf:"bytes,2,opt,name=OwnerToken,proto3" json:"OwnerToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClientOwnerTokenRequest) Reset() {
	*x = SetClientOwnerTokenRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClientOwnerTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClientOwnerTokenRequest) ProtoMessage() {}

func (x *SetClientOwnerTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClientOwnerTokenRequest.ProtoReflect.Descriptor instead.
func (*SetClientOwnerTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{27}
}

func (x *SetClientOwnerTokenRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *SetClientOwnerTokenRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

// SetClientOwnerTokenResponse indicates whether the token update succeeded.
type SetClientOwnerTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClientOwnerTokenResponse) Reset() {
	*x = SetClientOwnerTokenResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClientOwnerTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClientOwnerTokenResponse) ProtoMessage() {}

func (x *SetClientOwnerTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClientOwnerTokenResponse.ProtoReflect.Descriptor instead.
func (*SetClientOwnerTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{28}
}

func (x *SetClientOwnerTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicRequest) Reset() {
	*x = DeleteTopicRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicRequest) ProtoMessage() {}

func (x *DeleteTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicRequest.ProtoReflect.Descriptor instead.
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type DeleteTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicResponse) Reset() {
	*x = DeleteTopicResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicResponse) ProtoMessage() {}

func (x *DeleteTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicResponse.ProtoReflect.Descriptor instead.
func (*DeleteTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetClientSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientSubscriptionsRequest) Reset() {
	*x = GetClientSubscriptionsRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientSubscriptionsRequest) ProtoMessage() {}

func (x *GetClientSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetClientSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{32}
}

func (x *GetClientSubscriptionsRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type GetClientSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        map[string]*SubOption  `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is topic filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientSubscriptionsResponse) Reset() {
	*x = GetClientSubscriptionsResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientSubscriptionsResponse) ProtoMessage() {}

func (x *GetClientSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetClientSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{33}
}

func (x *GetClientSubscriptionsResponse) GetTopics() map[string]*SubOption {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetShareGroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareGroup    string                 `protobuf:"bytes,1,opt,name=ShareGroup,proto3" json:"ShareGroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareGroupMembersRequest) Reset() {
	*x = GetShareGroupMembersRequest{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareGroupMembersRequest) ProtoMessage() {}

func (x *GetShareGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*GetShareGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{34}
}

func (x *GetShareGroupMembersRequest) GetShareGroup() string {
	if x != nil {
		return x.ShareGroup
	}
	return ""
}

type ShareGroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	TopicFilter   string                 `protobuf:"bytes,2,opt,name=TopicFilter,proto3" json:"TopicFilter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareGroupMember) Reset() {
	*x = ShareGroupMember{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareGroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareGroupMember) ProtoMessage() {}

func (x *ShareGroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareGroupMember.ProtoReflect.Descriptor instead.
func (*ShareGroupMember) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{35}
}

func (x *ShareGroupMember) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ShareGroupMember) GetTopicFilter() string {
	if x != nil {
		return x.TopicFilter
	}
	return ""
}

type GetShareGroupMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ShareGroupMember    `protobuf:"bytes,1,rep,name=Members,proto3" json:"Members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareGroupMembersResponse) Reset() {
	*x = GetShareGroupMembersResponse{}
	mi := &file_proto_proto_topic_topic_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareGroupMembersResponse) ProtoMessage() {}

func (x *GetShareGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_topic_topic_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*GetShareGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_topic_topic_proto_rawDescGZIP(), []int{36}
}

func (x *GetShareGroupMembersResponse) GetMembers() []*ShareGroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_proto_proto_topic_topic_proto protoreflect.FileDescriptor

const file_proto_proto_topic_topic_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/proto_topic/topic.proto\x12\x05proto\"\xdb\x01\n" +
	"\tSubOption\x12\x10\n" +
	"\x03QoS\x18\x01 \x01(\x05R\x03QoS\x12,\n" +
	"\x11RetainAsPublished\x18\x02 \x01(\bR\x11RetainAsPublished\x12\x14\n" +
	"\x05Topic\x18\x03 \x01(\tR\x05Topic\x12\x18\n" +
	"\aNoLocal\x18\x04 \x01(\bR\aNoLocal\x12&\n" +
	"\x0eRetainHandling\x18\x05 \x01(\x05R\x0eRetainHandling\x126\n" +
	"\x16SubscriptionIdentifier\x18\x06 \x01(\x05R\x16SubscriptionIdentifier\"\x9c\x01\n" +
	"\x0eTopicClientsID\x12<\n" +
	"\aClients\x18\x01 \x03(\v2\".proto.TopicClientsID.ClientsEntryR\aClients\x1aL\n" +
	"\fClientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.SubOptionR\x05value:\x028\x01\";\n" +
	"\fTopicSubTree\x12+\n" +
	"\bTreeRoot\x18\x01 \x01(\v2\x0f.proto.TreeNodeR\bTreeRoot\"\xd3\x03\n" +
	"\bTreeNode\x12\"\n" +
	"\fTopicSection\x18\x01 \x01(\tR\fTopicSection\x12\x14\n" +
	"\x05Topic\x18\x02 \x01(\tR\x05Topic\x123\n" +
	"\x06Client\x18\x03 \x03(\v2\x1b.proto.TreeNode.ClientEntryR\x06Client\x12<\n" +
	"\tChildNode\x18\x04 \x03(\v2\x1e.proto.TreeNode.ChildNodeEntryR\tChildNode\x12?\n" +
	"\n" +
	"ClusterSub\x18\x05 \x03(\v2\x1f.proto.TreeNode.ClusterSubEntryR\n" +
	"ClusterSub\x1aK\n" +
	"\vClientEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.SubOptionR\x05value:\x028\x01\x1aM\n" +
	"\x0eChildNodeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.proto.TreeNodeR\x05value:\x028\x01\x1a=\n" +
	"\x0fClusterSubEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x98\x01\n" +
	"\x0eClientSubTopic\x129\n" +
	"\x06Topics\x18\x01 \x03(\v2!.proto.ClientSubTopic.TopicsEntryR\x06Topics\x1aK\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.SubOptionR\x05value:\x028\x01\"\x9f\x01\n" +
	"\rClientManager\x12;\n" +
	"\aClients\x18\x01 \x03(\v2!.proto.ClientManager.ClientsEntryR\aClients\x1aQ\n" +
	"\fClientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.proto.ClientSubTopicR\x05value:\x028\x01\"b\n" +
	"\aSubCore\x12'\n" +
	"\x04root\x18\x01 \x01(\v2\x13.proto.TopicSubTreeR\x04root\x12.\n" +
	"\aclients\x18\x02 \x01(\v2\x14.proto.ClientManagerR\aclients\"\xb0\x02\n" +
	"\n" +
	"ClusterSub\x128\n" +
	"\acluster\x18\x01 \x03(\v2\x1e.proto.ClusterSub.ClusterEntryR\acluster\x12V\n" +
	"\x11ClientOwnerTokens\x18\x02 \x03(\v2(.proto.ClusterSub.ClientOwnerTokensEntryR\x11ClientOwnerTokens\x1aJ\n" +
	"\fClusterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.proto.SubCoreR\x05value:\x028\x01\x1aD\n" +
	"\x16ClientOwnerTokensEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\rUpdateRequest\x12+\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x17.proto.TopicRequestTypeR\x04Type\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\x12\x1c\n" +
	"\tRequestID\x18\x03 \x01(\tR\tRequestID\"o\n" +
	"\x0eUpdateResponse\x12+\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x17.proto.TopicRequestTypeR\x04Type\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\x12\x1c\n" +
	"\tRequestID\x18\x03 \x01(\tR\tRequestID\"r\n" +
	"\n" +
	"SubRequest\x12(\n" +
	"\x06Topics\x18\x01 \x03(\v2\x10.proto.SubOptionR\x06Topics\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12\x1e\n" +
	"\n" +
	"OwnerToken\x18\x03 \x01(\tR\n" +
	"OwnerToken\"\x9a\x01\n" +
	"\vSubResponse\x126\n" +
	"\x06Topics\x18\x01 \x03(\v2\x1e.proto.SubResponse.TopicsEntryR\x06Topics\x12\x18\n" +
	"\aSuccess\x18\x02 \x01(\bR\aSuccess\x1a9\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x98\x01\n" +
	"\fUnSubRequest\x12\x16\n" +
	"\x06Topics\x18\x01 \x03(\tR\x06Topics\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12\x14\n" +
	"\x05Share\x18\x03 \x01(\bR\x05Share\x12\x1e\n" +
	"\n" +
	"ShareGroup\x18\x04 \x01(\tR\n" +
	"ShareGroup\x12\x1e\n" +
	"\n" +
	"OwnerToken\x18\x05 \x01(\tR\n" +
	"OwnerToken\"'\n" +
	"\rUnSubResponse\x12\x16\n" +
	"\x06Topics\x18\x01 \x03(\x05R\x06Topics\"0\n" +
	"\x18GetAllMatchTopicsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\x98\x01\n" +
	"\x19GetAllMatchTopicsResponse\x12A\n" +
	"\x05Topic\x18\x02 \x03(\v2+.proto.GetAllMatchTopicsResponse.TopicEntryR\x05Topic\x1a8\n" +
	"\n" +
	"TopicEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"<\n" +
	"$GetAllMatchTopicsForWildTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"=\n" +
	"%GetAllMatchTopicsForWildTopicResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x03(\tR\x05topic\"3\n" +
	"\x1bGetAllSubTopicClientRequest\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05Topic\"\xb4\x01\n" +
	"\x1cGetAllSubTopicClientResponse\x12G\n" +
	"\x06Client\x18\x01 \x03(\v2/.proto.GetAllSubTopicClientResponse.ClientEntryR\x06Client\x1aK\n" +
	"\vClientEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.SubOptionR\x05value:\x028\x01\"2\n" +
	"\x1aGetAllMatchClientV2Request\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05Topic\"\xf1\x01\n" +
	"\x13MatchedSubscription\x12 \n" +
	"\vTopicFilter\x18\x01 \x01(\tR\vTopicFilter\x12\x10\n" +
	"\x03QoS\x18\x02 \x01(\x05R\x03QoS\x12,\n" +
	"\x11RetainAsPublished\x18\x03 \x01(\bR\x11RetainAsPublished\x12\x18\n" +
	"\aNoLocal\x18\x04 \x01(\bR\aNoLocal\x12&\n" +
	"\x0eRetainHandling\x18\x05 \x01(\x05R\x0eRetainHandling\x126\n" +
	"\x16SubscriptionIdentifier\x18\x06 \x01(\x05R\x16SubscriptionIdentifier\"w\n" +
	"\vClientMatch\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\x16\n" +
	"\x06MaxQoS\x18\x02 \x01(\x05R\x06MaxQoS\x124\n" +
	"\aMatched\x18\x03 \x03(\v2\x1a.proto.MatchedSubscriptionR\aMatched\"K\n" +
	"\x1bGetAllMatchClientV2Response\x12,\n" +
	"\aMatches\x18\x01 \x03(\v2\x12.proto.ClientMatchR\aMatches\"E\n" +
	"\x11GetSubTreeRequest\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05Topic\x12\x1a\n" +
	"\bMaxDepth\x18\x02 \x01(\x05R\bMaxDepth\"9\n" +
	"\x12GetSubTreeResponse\x12#\n" +
	"\x04Root\x18\x01 \x01(\v2\x0f.proto.TreeNodeR\x04Root\"g\n" +
	"\x13DeleteClientRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\x14\n" +
	"\x05Topic\x18\x02 \x03(\tR\x05Topic\x12\x1e\n" +
	"\n" +
	"OwnerToken\x18\x03 \x01(\tR\n" +
	"OwnerToken\"X\n" +
	"\x1aSetClientOwnerTokenRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\x1e\n" +
	"\n" +
	"OwnerToken\x18\x02 \x01(\tR\n" +
	"OwnerToken\"7\n" +
	"\x1bSetClientOwnerTokenResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"0\n" +
	"\x14DeleteClientResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"*\n" +
	"\x12DeleteTopicRequest\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05Topic\"/\n" +
	"\x13DeleteTopicResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\";\n" +
	"\x1dGetClientSubscriptionsRequest\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\"\xb8\x01\n" +
	"\x1eGetClientSubscriptionsResponse\x12I\n" +
	"\x06Topics\x18\x01 \x03(\v21.proto.GetClientSubscriptionsResponse.TopicsEntryR\x06Topics\x1aK\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.SubOptionR\x05value:\x028\x01\"=\n" +
	"\x1bGetShareGroupMembersRequest\x12\x1e\n" +
	"\n" +
	"ShareGroup\x18\x01 \x01(\tR\n" +
	"ShareGroup\"P\n" +
	"\x10ShareGroupMember\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12 \n" +
	"\vTopicFilter\x18\x02 \x01(\tR\vTopicFilter\"Q\n" +
	"\x1cGetShareGroupMembersResponse\x121\n" +
	"\aMembers\x18\x01 \x03(\v2\x17.proto.ShareGroupMemberR\aMembers*b\n" +
	"\x10TopicRequestType\x12\a\n" +
	"\x03Sub\x10\x00\x12\t\n" +
	"\x05UnSub\x10\x01\x12\x10\n" +
	"\fDeleteClient\x10\x02\x12\x0f\n" +
	"\vDeleteTopic\x10\x03\x12\x17\n" +
	"\x13SetClientOwnerToken\x10\x04B\x10Z\x0e./;proto_topicb\x06proto3"

var (
	file_proto_proto_topic_topic_proto_rawDescOnce sync.Once
	file_proto_proto_topic_topic_proto_rawDescData []byte
)

func file_proto_proto_topic_topic_proto_rawDescGZIP() []byte {
	file_proto_proto_topic_topic_proto_rawDescOnce.Do(func() {
		file_proto_proto_topic_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_topic_topic_proto_rawDesc), len(file_proto_proto_topic_topic_proto_rawDesc)))
	})
	return file_proto_proto_topic_topic_proto_rawDescData
}

var file_proto_proto_topic_topic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_topic_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_proto_proto_topic_topic_proto_goTypes = []any{
	(TopicRequestType)(0),                         // 0: proto.TopicRequestType
	(*SubOption)(nil),                             // 1: proto.SubOption
	(*TopicClientsID)(nil),                        // 2: proto.TopicClientsID
	(*TopicSubTree)(nil),                          // 3: proto.TopicSubTree
	(*TreeNode)(nil),                              // 4: proto.TreeNode
	(*ClientSubTopic)(nil),                        // 5: proto.ClientSubTopic
	(*ClientManager)(nil),                         // 6: proto.ClientManager
	(*SubCore)(nil),                               // 7: proto.SubCore
	(*ClusterSub)(nil),                            // 8: proto.ClusterSub
	(*UpdateRequest)(nil),                         // 9: proto.UpdateRequest
	(*UpdateResponse)(nil),                        // 10: proto.UpdateResponse
	(*SubRequest)(nil),                            // 11: proto.SubRequest
	(*SubResponse)(nil),                           // 12: proto.SubResponse
	(*UnSubRequest)(nil),                          // 13: proto.UnSubRequest
	(*UnSubResponse)(nil),                         // 14: proto.UnSubResponse
	(*GetAllMatchTopicsRequest)(nil),              // 15: proto.GetAllMatchTopicsRequest
	(*GetAllMatchTopicsResponse)(nil),             // 16: proto.GetAllMatchTopicsResponse
	(*GetAllMatchTopicsForWildTopicRequest)(nil),  // 17: proto.GetAllMatchTopicsForWildTopicRequest
	(*GetAllMatchTopicsForWildTopicResponse)(nil), // 18: proto.GetAllMatchTopicsForWildTopicResponse
	(*GetAllSubTopicClientRequest)(nil),           // 19: proto.GetAllSubTopicClientRequest
	(*GetAllSubTopicClientResponse)(nil),          // 20: proto.GetAllSubTopicClientResponse
	(*GetAllMatchClientV2Request)(nil),            // 21: proto.GetAllMatchClientV2Request
	(*MatchedSubscription)(nil),                   // 22: proto.MatchedSubscription
	(*ClientMatch)(nil),                           // 23: proto.ClientMatch
	(*GetAllMatchClientV2Response)(nil),           // 24: proto.GetAllMatchClientV2Response
	(*GetSubTreeRequest)(nil),                     // 25: proto.GetSubTreeRequest
	(*GetSubTreeResponse)(nil),                    // 26: proto.GetSubTreeResponse
	(*DeleteClientRequest)(nil),                   // 27: proto.DeleteClientRequest
	(*SetClientOwnerTokenRequest)(nil),            // 28: proto.SetClientOwnerTokenRequest
	(*SetClientOwnerTokenResponse)(nil),           // 29: proto.SetClientOwnerTokenResponse
	(*DeleteClientResponse)(nil),                  // 30: proto.DeleteClientResponse
	(*DeleteTopicRequest)(nil),                    // 31: proto.DeleteTopicRequest
	(*DeleteTopicResponse)(nil),                   // 32: proto.DeleteTopicResponse
	(*GetClientSubscriptionsRequest)(nil),         // 33: proto.GetClientSubscriptionsRequest
	(*GetClientSubscriptionsResponse)(nil),        // 34: proto.GetClientSubscriptionsResponse
	(*GetShareGroupMembersRequest)(nil),           // 35: proto.GetShareGroupMembersRequest
	(*ShareGroupMember)(nil),                      // 36: proto.ShareGroupMember
	(*GetShareGroupMembersResponse)(nil),          // 37: proto.GetShareGroupMembersResponse
	nil,                                           // 38: proto.TopicClientsID.ClientsEntry
	nil,                                           // 39: proto.TreeNode.ClientEntry
	nil,                                           // 40: proto.TreeNode.ChildNodeEntry
	nil,                                           // 41: proto.TreeNode.ClusterSubEntry
	nil,                                           // 42: proto.ClientSubTopic.TopicsEntry
	nil,                                           // 43: proto.ClientManager.ClientsEntry
	nil,                                           // 44: proto.ClusterSub.ClusterEntry
	nil,                                           // 45: proto.ClusterSub.ClientOwnerTokensEntry
	nil,                                           // 46: proto.SubResponse.TopicsEntry
	nil,                                           // 47: proto.GetAllMatchTopicsResponse.TopicEntry
	nil,                                           // 48: proto.GetAllSubTopicClientResponse.ClientEntry
	nil,                                           // 49: proto.GetClientSubscriptionsResponse.TopicsEntry
}
var file_proto_proto_topic_topic_proto_depIdxs = []int32{
	38, // 0: proto.TopicClientsID.Clients:type_name -> proto.TopicClientsID.ClientsEntry
	4,  // 1: proto.TopicSubTree.TreeRoot:type_name -> proto.TreeNode
	39, // 2: proto.TreeNode.Client:type_name -> proto.TreeNode.ClientEntry
	40, // 3: proto.TreeNode.ChildNode:type_name -> proto.TreeNode.ChildNodeEntry
	41, // 4: proto.TreeNode.ClusterSub:type_name -> proto.TreeNode.ClusterSubEntry
	42, // 5: proto.ClientSubTopic.Topics:type_name -> proto.ClientSubTopic.TopicsEntry
	43, // 6: proto.ClientManager.Clients:type_name -> proto.ClientManager.ClientsEntry
	3,  // 7: proto.SubCore.root:type_name -> proto.TopicSubTree
	6,  // 8: proto.SubCore.clients:type_name -> proto.ClientManager
	44, // 9: proto.ClusterSub.cluster:type_name -> proto.ClusterSub.ClusterEntry
	45, // 10: proto.ClusterSub.ClientOwnerTokens:type_name -> proto.ClusterSub.ClientOwnerTokensEntry
	0,  // 11: proto.UpdateRequest.Type:type_name -> proto.TopicRequestType
	0,  // 12: proto.UpdateResponse.Type:type_name -> proto.TopicRequestType
	1,  // 13: proto.SubRequest.Topics:type_name -> proto.SubOption
	46, // 14: proto.SubResponse.Topics:type_name -> proto.SubResponse.TopicsEntry
	47, // 15: proto.GetAllMatchTopicsResponse.Topic:type_name -> proto.GetAllMatchTopicsResponse.TopicEntry
	48, // 16: proto.GetAllSubTopicClientResponse.Client:type_name -> proto.GetAllSubTopicClientResponse.ClientEntry
	22, // 17: proto.ClientMatch.Matched:type_name -> proto.MatchedSubscription
	23, // 18: proto.GetAllMatchClientV2Response.Matches:type_name -> proto.ClientMatch
	4,  // 19: proto.GetSubTreeResponse.Root:type_name -> proto.TreeNode
	49, // 20: proto.GetClientSubscriptionsResponse.Topics:type_name -> proto.GetClientSubscriptionsResponse.TopicsEntry
	36, // 21: proto.GetShareGroupMembersResponse.Members:type_name -> proto.ShareGroupMember
	1,  // 22: proto.TopicClientsID.ClientsEntry.value:type_name -> proto.SubOption
	1,  // 23: proto.TreeNode.ClientEntry.value:type_name -> proto.SubOption
	4,  // 24: proto.TreeNode.ChildNodeEntry.value:type_name -> proto.TreeNode
	1,  // 25: proto.ClientSubTopic.TopicsEntry.value:type_name -> proto.SubOption
	5,  // 26: proto.ClientManager.ClientsEntry.value:type_name -> proto.ClientSubTopic
	7,  // 27: proto.ClusterSub.ClusterEntry.value:type_name -> proto.SubCore
	1,  // 28: proto.GetAllSubTopicClientResponse.ClientEntry.value:type_name -> proto.SubOption
	1,  // 29: proto.GetClientSubscriptionsResponse.TopicsEntry.value:type_name -> proto.SubOption
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_proto_topic_topic_proto_init() }
func file_proto_proto_topic_topic_proto_init() {
	if File_proto_proto_topic_topic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_topic_topic_proto_rawDesc), len(file_proto_proto_topic_topic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_topic_topic_proto_goTypes,
		DependencyIndexes: file_proto_proto_topic_topic_proto_depIdxs,
		EnumInfos:         file_proto_proto_topic_topic_proto_enumTypes,
		MessageInfos:      file_proto_proto_topic_topic_proto_msgTypes,
	}.Build()
	File_proto_proto_topic_topic_proto = out.File
	file_proto_proto_topic_topic_proto_goTypes = nil
	file_proto_proto_topic_topic_proto_depIdxs = nil
}
