// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/proto_auth/auth.proto

package proto_auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthRequest 认证请求
type AuthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                   // 客户端ID
	ReasonCode     uint32                 `protobuf:"varint,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`            // 原因码
	AuthMethod     string                 `protobuf:"bytes,3,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`             // 认证方法
	AuthData       []byte                 `protobuf:"bytes,4,opt,name=auth_data,json=authData,proto3" json:"auth_data,omitempty"`                   // 认证数据
	ReasonString   string                 `protobuf:"bytes,5,opt,name=reason_string,json=reasonString,proto3" json:"reason_string,omitempty"`       // 原因字符串
	UserProperties []*UserProperty        `protobuf:"bytes,6,rep,name=user_properties,json=userProperties,proto3" json:"user_properties,omitempty"` // 用户属性
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthRequest) GetReasonCode() uint32 {
	if x != nil {
		return x.ReasonCode
	}
	return 0
}

func (x *AuthRequest) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *AuthRequest) GetAuthData() []byte {
	if x != nil {
		return x.AuthData
	}
	return nil
}

func (x *AuthRequest) GetReasonString() string {
	if x != nil {
		return x.ReasonString
	}
	return ""
}

func (x *AuthRequest) GetUserProperties() []*UserProperty {
	if x != nil {
		return x.UserProperties
	}
	return nil
}

// AuthResponse 认证响应
type AuthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReasonCode     uint32                 `protobuf:"varint,1,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`            // 原因码
	AuthMethod     string                 `protobuf:"bytes,2,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`             // 认证方法
	AuthData       []byte                 `protobuf:"bytes,3,opt,name=auth_data,json=authData,proto3" json:"auth_data,omitempty"`                   // 认证数据
	ReasonString   string                 `protobuf:"bytes,4,opt,name=reason_string,json=reasonString,proto3" json:"reason_string,omitempty"`       // 原因字符串
	UserProperties []*UserProperty        `protobuf:"bytes,5,rep,name=user_properties,json=userProperties,proto3" json:"user_properties,omitempty"` // 用户属性
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetReasonCode() uint32 {
	if x != nil {
		return x.ReasonCode
	}
	return 0
}

func (x *AuthResponse) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *AuthResponse) GetAuthData() []byte {
	if x != nil {
		return x.AuthData
	}
	return nil
}

func (x *AuthResponse) GetReasonString() string {
	if x != nil {
		return x.ReasonString
	}
	return ""
}

func (x *AuthResponse) GetUserProperties() []*UserProperty {
	if x != nil {
		return x.UserProperties
	}
	return nil
}

// UserProperty 用户属性
type UserProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProperty) Reset() {
	*x = UserProperty{}
	mi := &file_proto_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProperty) ProtoMessage() {}

func (x *UserProperty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProperty.ProtoReflect.Descriptor instead.
func (*UserProperty) Descriptor() ([]byte, []int) {
	return file_proto_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UserProperty) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserProperty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_proto_auth_auth_proto protoreflect.FileDescriptor

const file_proto_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/proto_auth/auth.proto\x12\n" +
	"proto_auth\"\xf1\x01\n" +
	"\vAuthRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vreason_code\x18\x02 \x01(\rR\n" +
	"reasonCode\x12\x1f\n" +
	"\vauth_method\x18\x03 \x01(\tR\n" +
	"authMethod\x12\x1b\n" +
	"\tauth_data\x18\x04 \x01(\fR\bauthData\x12#\n" +
	"\rreason_string\x18\x05 \x01(\tR\freasonString\x12A\n" +
	"\x0fuser_properties\x18\x06 \x03(\v2\x18.proto_auth.UserPropertyR\x0euserProperties\"\xd5\x01\n" +
	"\fAuthResponse\x12\x1f\n" +
	"\vreason_code\x18\x01 \x01(\rR\n" +
	"reasonCode\x12\x1f\n" +
	"\vauth_method\x18\x02 \x01(\tR\n" +
	"authMethod\x12\x1b\n" +
	"\tauth_data\x18\x03 \x01(\fR\bauthData\x12#\n" +
	"\rreason_string\x18\x04 \x01(\tR\freasonString\x12A\n" +
	"\x0fuser_properties\x18\x05 \x03(\v2\x18.proto_auth.UserPropertyR\x0euserProperties\"6\n" +
	"\fUserProperty\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2P\n" +
	"\vAuthService\x12A\n" +
	"\fAuthenticate\x12\x17.proto_auth.AuthRequest\x1a\x18.proto_auth.AuthResponseB,Z*github.com/BAN1ce/skyTree/proto/proto_authb\x06proto3"

var (
	file_proto_proto_auth_auth_proto_rawDescOnce sync.Once
	file_proto_proto_auth_auth_proto_rawDescData []byte
)

func file_proto_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_proto_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_proto_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_auth_auth_proto_rawDesc), len(file_proto_proto_auth_auth_proto_rawDesc)))
	})
	return file_proto_proto_auth_auth_proto_rawDescData
}

var file_proto_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_proto_auth_auth_proto_goTypes = []any{
	(*AuthRequest)(nil),  // 0: proto_auth.AuthRequest
	(*AuthResponse)(nil), // 1: proto_auth.AuthResponse
	(*UserProperty)(nil), // 2: proto_auth.UserProperty
}
var file_proto_proto_auth_auth_proto_depIdxs = []int32{
	2, // 0: proto_auth.AuthRequest.user_properties:type_name -> proto_auth.UserProperty
	2, // 1: proto_auth.AuthResponse.user_properties:type_name -> proto_auth.UserProperty
	0, // 2: proto_auth.AuthService.Authenticate:input_type -> proto_auth.AuthRequest
	1, // 3: proto_auth.AuthService.Authenticate:output_type -> proto_auth.AuthResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_proto_auth_auth_proto_init() }
func file_proto_proto_auth_auth_proto_init() {
	if File_proto_proto_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_auth_auth_proto_rawDesc), len(file_proto_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_proto_auth_auth_proto_depIdxs,
		MessageInfos:      file_proto_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_proto_proto_auth_auth_proto = out.File
	file_proto_proto_auth_auth_proto_goTypes = nil
	file_proto_proto_auth_auth_proto_depIdxs = nil
}
