// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/proto_event/request.proto

package proto_event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_ADD_LISTENER    RequestType = 0
	RequestType_DELETE_LISTENER RequestType = 1
	RequestType_EMIT_EVENT      RequestType = 2
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "ADD_LISTENER",
		1: "DELETE_LISTENER",
		2: "EMIT_EVENT",
	}
	RequestType_value = map[string]int32{
		"ADD_LISTENER":    0,
		"DELETE_LISTENER": 1,
		"EMIT_EVENT":      2,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_event_request_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_proto_proto_event_request_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_event_request_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type          RequestType            `protobuf:"varint,2,opt,name=Type,proto3,enum=event.RequestType" json:"Type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Time          int64                  `protobuf:"varint,4,opt,name=Time,proto3" json:"Time,omitempty"`
	RequestNodeID uint64                 `protobuf:"varint,6,opt,name=RequestNodeID,proto3" json:"RequestNodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_proto_event_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_event_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_proto_event_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Request) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_ADD_LISTENER
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Request) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Request) GetRequestNodeID() uint64 {
	if x != nil {
		return x.RequestNodeID
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type          RequestType            `protobuf:"varint,2,opt,name=Type,proto3,enum=event.RequestType" json:"Type,omitempty"`
	Result        bool                   `protobuf:"varint,3,opt,name=Result,proto3" json:"Result,omitempty"`
	ListenNodes   []uint64               `protobuf:"varint,4,rep,packed,name=ListenNodes,proto3" json:"ListenNodes,omitempty"`
	Time          int64                  `protobuf:"varint,5,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_proto_event_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_event_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_proto_event_request_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Response) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_ADD_LISTENER
}

func (x *Response) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *Response) GetListenNodes() []uint64 {
	if x != nil {
		return x.ListenNodes
	}
	return nil
}

func (x *Response) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// request for adding listener for node
type AddListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	NodeID        uint64                 `protobuf:"varint,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Once          bool                   `protobuf:"varint,4,opt,name=Once,proto3" json:"Once,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListenerRequest) Reset() {
	*x = AddListenerRequest{}
	mi := &file_proto_proto_event_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListenerRequest) ProtoMessage() {}

func (x *AddListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_event_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListenerRequest.ProtoReflect.Descriptor instead.
func (*AddListenerRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_event_request_proto_rawDescGZIP(), []int{2}
}

func (x *AddListenerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddListenerRequest) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *AddListenerRequest) GetOnce() bool {
	if x != nil {
		return x.Once
	}
	return false
}

// request for deleting listener for node
type DeleteListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	NodeID        uint64                 `protobuf:"varint,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=Node,proto3" json:"Node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListenerRequest) Reset() {
	*x = DeleteListenerRequest{}
	mi := &file_proto_proto_event_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListenerRequest) ProtoMessage() {}

func (x *DeleteListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_event_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListenerRequest.ProtoReflect.Descriptor instead.
func (*DeleteListenerRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_event_request_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteListenerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteListenerRequest) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *DeleteListenerRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type ReadEventListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=EventName,proto3" json:"EventName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEventListenerRequest) Reset() {
	*x = ReadEventListenerRequest{}
	mi := &file_proto_proto_event_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEventListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEventListenerRequest) ProtoMessage() {}

func (x *ReadEventListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_event_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEventListenerRequest.ProtoReflect.Descriptor instead.
func (*ReadEventListenerRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_event_request_proto_rawDescGZIP(), []int{4}
}

func (x *ReadEventListenerRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type ReadEventListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []uint64               `protobuf:"varint,1,rep,packed,name=Nodes,proto3" json:"Nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEventListenerResponse) Reset() {
	*x = ReadEventListenerResponse{}
	mi := &file_proto_proto_event_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEventListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEventListenerResponse) ProtoMessage() {}

func (x *ReadEventListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_event_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEventListenerResponse.ProtoReflect.Descriptor instead.
func (*ReadEventListenerResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_event_request_proto_rawDescGZIP(), []int{5}
}

func (x *ReadEventListenerResponse) GetNodes() []uint64 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PublishDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeID        uint64                 `protobuf:"varint,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishDoneRequest) Reset() {
	*x = PublishDoneRequest{}
	mi := &file_proto_proto_event_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishDoneRequest) ProtoMessage() {}

func (x *PublishDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_event_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishDoneRequest.ProtoReflect.Descriptor instead.
func (*PublishDoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_event_request_proto_rawDescGZIP(), []int{6}
}

func (x *PublishDoneRequest) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *PublishDoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishDoneRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_proto_event_request_proto protoreflect.FileDescriptor

const file_proto_proto_event_request_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/proto_event/request.proto\x12\x05event\"\x95\x01\n" +
	"\aRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12&\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x12.event.RequestTypeR\x04Type\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x12\n" +
	"\x04Time\x18\x04 \x01(\x03R\x04Time\x12$\n" +
	"\rRequestNodeID\x18\x06 \x01(\x04R\rRequestNodeIDJ\x04\b\x05\x10\x06\"\x90\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12&\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x12.event.RequestTypeR\x04Type\x12\x16\n" +
	"\x06Result\x18\x03 \x01(\bR\x06Result\x12 \n" +
	"\vListenNodes\x18\x04 \x03(\x04R\vListenNodes\x12\x12\n" +
	"\x04Time\x18\x05 \x01(\x03R\x04Time\"T\n" +
	"\x12AddListenerRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06NodeID\x18\x02 \x01(\x04R\x06NodeID\x12\x12\n" +
	"\x04Once\x18\x04 \x01(\bR\x04Once\"W\n" +
	"\x15DeleteListenerRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06NodeID\x18\x02 \x01(\x04R\x06NodeID\x12\x12\n" +
	"\x04Node\x18\x03 \x01(\tR\x04Node\"8\n" +
	"\x18ReadEventListenerRequest\x12\x1c\n" +
	"\tEventName\x18\x01 \x01(\tR\tEventName\"1\n" +
	"\x19ReadEventListenerResponse\x12\x14\n" +
	"\x05Nodes\x18\x01 \x03(\x04R\x05Nodes\"T\n" +
	"\x12PublishDoneRequest\x12\x16\n" +
	"\x06NodeID\x18\x01 \x01(\x04R\x06NodeID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data*D\n" +
	"\vRequestType\x12\x10\n" +
	"\fADD_LISTENER\x10\x00\x12\x13\n" +
	"\x0fDELETE_LISTENER\x10\x01\x12\x0e\n" +
	"\n" +
	"EMIT_EVENT\x10\x02B\x10Z\x0e./;proto_eventb\x06proto3"

var (
	file_proto_proto_event_request_proto_rawDescOnce sync.Once
	file_proto_proto_event_request_proto_rawDescData []byte
)

func file_proto_proto_event_request_proto_rawDescGZIP() []byte {
	file_proto_proto_event_request_proto_rawDescOnce.Do(func() {
		file_proto_proto_event_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_event_request_proto_rawDesc), len(file_proto_proto_event_request_proto_rawDesc)))
	})
	return file_proto_proto_event_request_proto_rawDescData
}

var file_proto_proto_event_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_event_request_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_proto_event_request_proto_goTypes = []any{
	(RequestType)(0),                  // 0: event.RequestType
	(*Request)(nil),                   // 1: event.Request
	(*Response)(nil),                  // 2: event.Response
	(*AddListenerRequest)(nil),        // 3: event.AddListenerRequest
	(*DeleteListenerRequest)(nil),     // 4: event.DeleteListenerRequest
	(*ReadEventListenerRequest)(nil),  // 5: event.ReadEventListenerRequest
	(*ReadEventListenerResponse)(nil), // 6: event.ReadEventListenerResponse
	(*PublishDoneRequest)(nil),        // 7: event.PublishDoneRequest
}
var file_proto_proto_event_request_proto_depIdxs = []int32{
	0, // 0: event.Request.Type:type_name -> event.RequestType
	0, // 1: event.Response.Type:type_name -> event.RequestType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_proto_event_request_proto_init() }
func file_proto_proto_event_request_proto_init() {
	if File_proto_proto_event_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_event_request_proto_rawDesc), len(file_proto_proto_event_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_event_request_proto_goTypes,
		DependencyIndexes: file_proto_proto_event_request_proto_depIdxs,
		EnumInfos:         file_proto_proto_event_request_proto_enumTypes,
		MessageInfos:      file_proto_proto_event_request_proto_msgTypes,
	}.Build()
	File_proto_proto_event_request_proto = out.File
	file_proto_proto_event_request_proto_goTypes = nil
	file_proto_proto_event_request_proto_depIdxs = nil
}
