// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/proto_will_delay/will_delay.proto

package proto_will_delay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WillDelayRequestType identifies the operation carried by WillDelayRequest.
type WillDelayRequestType int32

const (
	WillDelayRequestType_ADD_TASK      WillDelayRequestType = 0
	WillDelayRequestType_DELETE_TASK   WillDelayRequestType = 1
	WillDelayRequestType_GET_DUE_TASKS WillDelayRequestType = 2
)

// Enum value maps for WillDelayRequestType.
var (
	WillDelayRequestType_name = map[int32]string{
		0: "ADD_TASK",
		1: "DELETE_TASK",
		2: "GET_DUE_TASKS",
	}
	WillDelayRequestType_value = map[string]int32{
		"ADD_TASK":      0,
		"DELETE_TASK":   1,
		"GET_DUE_TASKS": 2,
	}
)

func (x WillDelayRequestType) Enum() *WillDelayRequestType {
	p := new(WillDelayRequestType)
	*p = x
	return p
}

func (x WillDelayRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WillDelayRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_will_delay_will_delay_proto_enumTypes[0].Descriptor()
}

func (WillDelayRequestType) Type() protoreflect.EnumType {
	return &file_proto_proto_will_delay_will_delay_proto_enumTypes[0]
}

func (x WillDelayRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WillDelayRequestType.Descriptor instead.
func (WillDelayRequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_will_delay_will_delay_proto_rawDescGZIP(), []int{0}
}

// WillDelayTask describes a scheduled will-delay task.
type WillDelayTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ClientID is the MQTT client identifier.
	ClientID string `protobuf:"bytes,1,opt,name=ClientID,json=client_id,proto3" json:"ClientID,omitempty"`
	// ScheduledPublishTime is the planned publish time in Unix microseconds.
	ScheduledPublishTime int64 `protobuf:"varint,2,opt,name=ScheduledPublishTime,json=scheduled_publish_time,proto3" json:"ScheduledPublishTime,omitempty"`
	// OwnerToken fences stale tasks from previous connections.
	OwnerToken    string `protobuf:"bytes,3,opt,name=OwnerToken,json=owner_token,proto3" json:"OwnerToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WillDelayTask) Reset() {
	*x = WillDelayTask{}
	mi := &file_proto_proto_will_delay_will_delay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WillDelayTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WillDelayTask) ProtoMessage() {}

func (x *WillDelayTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_will_delay_will_delay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WillDelayTask.ProtoReflect.Descriptor instead.
func (*WillDelayTask) Descriptor() ([]byte, []int) {
	return file_proto_proto_will_delay_will_delay_proto_rawDescGZIP(), []int{0}
}

func (x *WillDelayTask) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *WillDelayTask) GetScheduledPublishTime() int64 {
	if x != nil {
		return x.ScheduledPublishTime
	}
	return 0
}

func (x *WillDelayTask) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

// WillDelayState stores all pending tasks for snapshot persistence.
type WillDelayState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tasks maps task keys to pending tasks.
	Tasks         map[string]*WillDelayTask `protobuf:"bytes,1,rep,name=Tasks,json=tasks,proto3" json:"Tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WillDelayState) Reset() {
	*x = WillDelayState{}
	mi := &file_proto_proto_will_delay_will_delay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WillDelayState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WillDelayState) ProtoMessage() {}

func (x *WillDelayState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_will_delay_will_delay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WillDelayState.ProtoReflect.Descriptor instead.
func (*WillDelayState) Descriptor() ([]byte, []int) {
	return file_proto_proto_will_delay_will_delay_proto_rawDescGZIP(), []int{1}
}

func (x *WillDelayState) GetTasks() map[string]*WillDelayTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// WillDelayRequest is the state-machine request envelope.
type WillDelayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  WillDelayRequestType   `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=proto_will_delay.WillDelayRequestType" json:"Type,omitempty"`
	// Task is used when adding a will-delay task.
	Task *WillDelayTask `protobuf:"bytes,2,opt,name=Task,json=task,proto3,oneof" json:"Task,omitempty"`
	// ClientID is used when deleting tasks for a client.
	ClientID *string `protobuf:"bytes,3,opt,name=ClientID,json=client_id,proto3,oneof" json:"ClientID,omitempty"`
	// CurrentTime is used when querying due tasks, in Unix microseconds.
	CurrentTime   *int64 `protobuf:"varint,4,opt,name=CurrentTime,json=current_time,proto3,oneof" json:"CurrentTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WillDelayRequest) Reset() {
	*x = WillDelayRequest{}
	mi := &file_proto_proto_will_delay_will_delay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WillDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WillDelayRequest) ProtoMessage() {}

func (x *WillDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_will_delay_will_delay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WillDelayRequest.ProtoReflect.Descriptor instead.
func (*WillDelayRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_will_delay_will_delay_proto_rawDescGZIP(), []int{2}
}

func (x *WillDelayRequest) GetType() WillDelayRequestType {
	if x != nil {
		return x.Type
	}
	return WillDelayRequestType_ADD_TASK
}

func (x *WillDelayRequest) GetTask() *WillDelayTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *WillDelayRequest) GetClientID() string {
	if x != nil && x.ClientID != nil {
		return *x.ClientID
	}
	return ""
}

func (x *WillDelayRequest) GetCurrentTime() int64 {
	if x != nil && x.CurrentTime != nil {
		return *x.CurrentTime
	}
	return 0
}

// WillDelayResponse is returned by will-delay state-machine lookups.
type WillDelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DueClientIDs contains client IDs whose tasks are due.
	DueClientIDs []string `protobuf:"bytes,1,rep,name=DueClientIDs,json=due_client_ids,proto3" json:"DueClientIDs,omitempty"`
	// Success indicates whether the lookup succeeded.
	Success bool `protobuf:"varint,2,opt,name=Success,json=success,proto3" json:"Success,omitempty"`
	// DueTasks contains tasks whose scheduled publish time is at or before current_time.
	DueTasks      []*WillDelayTask `protobuf:"bytes,3,rep,name=DueTasks,json=due_tasks,proto3" json:"DueTasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WillDelayResponse) Reset() {
	*x = WillDelayResponse{}
	mi := &file_proto_proto_will_delay_will_delay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WillDelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WillDelayResponse) ProtoMessage() {}

func (x *WillDelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_will_delay_will_delay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WillDelayResponse.ProtoReflect.Descriptor instead.
func (*WillDelayResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_will_delay_will_delay_proto_rawDescGZIP(), []int{3}
}

func (x *WillDelayResponse) GetDueClientIDs() []string {
	if x != nil {
		return x.DueClientIDs
	}
	return nil
}

func (x *WillDelayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WillDelayResponse) GetDueTasks() []*WillDelayTask {
	if x != nil {
		return x.DueTasks
	}
	return nil
}

var File_proto_proto_will_delay_will_delay_proto protoreflect.FileDescriptor

const file_proto_proto_will_delay_will_delay_proto_rawDesc = "" +
	"\n" +
	"'proto/proto_will_delay/will_delay.proto\x12\x10proto_will_delay\"\x83\x01\n" +
	"\rWillDelayTask\x12\x1b\n" +
	"\bClientID\x18\x01 \x01(\tR\tclient_id\x124\n" +
	"\x14ScheduledPublishTime\x18\x02 \x01(\x03R\x16scheduled_publish_time\x12\x1f\n" +
	"\n" +
	"OwnerToken\x18\x03 \x01(\tR\vowner_token\"\xae\x01\n" +
	"\x0eWillDelayState\x12A\n" +
	"\x05Tasks\x18\x01 \x03(\v2+.proto_will_delay.WillDelayState.TasksEntryR\x05tasks\x1aY\n" +
	"\n" +
	"TasksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.proto_will_delay.WillDelayTaskR\x05value:\x028\x01\"\xf8\x01\n" +
	"\x10WillDelayRequest\x12:\n" +
	"\x04Type\x18\x01 \x01(\x0e2&.proto_will_delay.WillDelayRequestTypeR\x04type\x128\n" +
	"\x04Task\x18\x02 \x01(\v2\x1f.proto_will_delay.WillDelayTaskH\x00R\x04task\x88\x01\x01\x12 \n" +
	"\bClientID\x18\x03 \x01(\tH\x01R\tclient_id\x88\x01\x01\x12&\n" +
	"\vCurrentTime\x18\x04 \x01(\x03H\x02R\fcurrent_time\x88\x01\x01B\a\n" +
	"\x05_TaskB\v\n" +
	"\t_ClientIDB\x0e\n" +
	"\f_CurrentTime\"\x91\x01\n" +
	"\x11WillDelayResponse\x12$\n" +
	"\fDueClientIDs\x18\x01 \x03(\tR\x0edue_client_ids\x12\x18\n" +
	"\aSuccess\x18\x02 \x01(\bR\asuccess\x12<\n" +
	"\bDueTasks\x18\x03 \x03(\v2\x1f.proto_will_delay.WillDelayTaskR\tdue_tasks*H\n" +
	"\x14WillDelayRequestType\x12\f\n" +
	"\bADD_TASK\x10\x00\x12\x0f\n" +
	"\vDELETE_TASK\x10\x01\x12\x11\n" +
	"\rGET_DUE_TASKS\x10\x02B2Z0github.com/BAN1ce/skyTree/proto/proto_will_delayb\x06proto3"

var (
	file_proto_proto_will_delay_will_delay_proto_rawDescOnce sync.Once
	file_proto_proto_will_delay_will_delay_proto_rawDescData []byte
)

func file_proto_proto_will_delay_will_delay_proto_rawDescGZIP() []byte {
	file_proto_proto_will_delay_will_delay_proto_rawDescOnce.Do(func() {
		file_proto_proto_will_delay_will_delay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_will_delay_will_delay_proto_rawDesc), len(file_proto_proto_will_delay_will_delay_proto_rawDesc)))
	})
	return file_proto_proto_will_delay_will_delay_proto_rawDescData
}

var file_proto_proto_will_delay_will_delay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_will_delay_will_delay_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_proto_will_delay_will_delay_proto_goTypes = []any{
	(WillDelayRequestType)(0), // 0: proto_will_delay.WillDelayRequestType
	(*WillDelayTask)(nil),     // 1: proto_will_delay.WillDelayTask
	(*WillDelayState)(nil),    // 2: proto_will_delay.WillDelayState
	(*WillDelayRequest)(nil),  // 3: proto_will_delay.WillDelayRequest
	(*WillDelayResponse)(nil), // 4: proto_will_delay.WillDelayResponse
	nil,                       // 5: proto_will_delay.WillDelayState.TasksEntry
}
var file_proto_proto_will_delay_will_delay_proto_depIdxs = []int32{
	5, // 0: proto_will_delay.WillDelayState.Tasks:type_name -> proto_will_delay.WillDelayState.TasksEntry
	0, // 1: proto_will_delay.WillDelayRequest.Type:type_name -> proto_will_delay.WillDelayRequestType
	1, // 2: proto_will_delay.WillDelayRequest.Task:type_name -> proto_will_delay.WillDelayTask
	1, // 3: proto_will_delay.WillDelayResponse.DueTasks:type_name -> proto_will_delay.WillDelayTask
	1, // 4: proto_will_delay.WillDelayState.TasksEntry.value:type_name -> proto_will_delay.WillDelayTask
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_proto_will_delay_will_delay_proto_init() }
func file_proto_proto_will_delay_will_delay_proto_init() {
	if File_proto_proto_will_delay_will_delay_proto != nil {
		return
	}
	file_proto_proto_will_delay_will_delay_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_will_delay_will_delay_proto_rawDesc), len(file_proto_proto_will_delay_will_delay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_will_delay_will_delay_proto_goTypes,
		DependencyIndexes: file_proto_proto_will_delay_will_delay_proto_depIdxs,
		EnumInfos:         file_proto_proto_will_delay_will_delay_proto_enumTypes,
		MessageInfos:      file_proto_proto_will_delay_will_delay_proto_msgTypes,
	}.Build()
	File_proto_proto_will_delay_will_delay_proto = out.File
	file_proto_proto_will_delay_will_delay_proto_goTypes = nil
	file_proto_proto_will_delay_will_delay_proto_depIdxs = nil
}
