// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/proto_retain/retain.proto

package proto_retain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetainMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Topic             string                 `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Payload           []byte                 `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Qos               int32                  `protobuf:"varint,3,opt,name=Qos,proto3" json:"Qos,omitempty"`
	PublishPacket     []byte                 `protobuf:"bytes,4,opt,name=PublishPacket,proto3" json:"PublishPacket,omitempty"`
	CreatedAtUnixNano int64                  `protobuf:"varint,5,opt,name=CreatedAtUnixNano,proto3" json:"CreatedAtUnixNano,omitempty"`
	PublisherClientID string                 `protobuf:"bytes,6,opt,name=PublisherClientID,proto3" json:"PublisherClientID,omitempty"`
	ExpiredAtUnixNano int64                  `protobuf:"varint,7,opt,name=ExpiredAtUnixNano,proto3" json:"ExpiredAtUnixNano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetainMessage) Reset() {
	*x = RetainMessage{}
	mi := &file_proto_proto_retain_retain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainMessage) ProtoMessage() {}

func (x *RetainMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_retain_retain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainMessage.ProtoReflect.Descriptor instead.
func (*RetainMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_retain_retain_proto_rawDescGZIP(), []int{0}
}

func (x *RetainMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RetainMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RetainMessage) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *RetainMessage) GetPublishPacket() []byte {
	if x != nil {
		return x.PublishPacket
	}
	return nil
}

func (x *RetainMessage) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

func (x *RetainMessage) GetPublisherClientID() string {
	if x != nil {
		return x.PublisherClientID
	}
	return ""
}

func (x *RetainMessage) GetExpiredAtUnixNano() int64 {
	if x != nil {
		return x.ExpiredAtUnixNano
	}
	return 0
}

var File_proto_proto_retain_retain_proto protoreflect.FileDescriptor

const file_proto_proto_retain_retain_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/proto_retain/retain.proto\x12\x05proto\"\x81\x02\n" +
	"\rRetainMessage\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05Topic\x12\x18\n" +
	"\aPayload\x18\x02 \x01(\fR\aPayload\x12\x10\n" +
	"\x03Qos\x18\x03 \x01(\x05R\x03Qos\x12$\n" +
	"\rPublishPacket\x18\x04 \x01(\fR\rPublishPacket\x12,\n" +
	"\x11CreatedAtUnixNano\x18\x05 \x01(\x03R\x11CreatedAtUnixNano\x12,\n" +
	"\x11PublisherClientID\x18\x06 \x01(\tR\x11PublisherClientID\x12,\n" +
	"\x11ExpiredAtUnixNano\x18\a \x01(\x03R\x11ExpiredAtUnixNanoB\x11Z\x0f./;proto_retainb\x06proto3"

var (
	file_proto_proto_retain_retain_proto_rawDescOnce sync.Once
	file_proto_proto_retain_retain_proto_rawDescData []byte
)

func file_proto_proto_retain_retain_proto_rawDescGZIP() []byte {
	file_proto_proto_retain_retain_proto_rawDescOnce.Do(func() {
		file_proto_proto_retain_retain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_retain_retain_proto_rawDesc), len(file_proto_proto_retain_retain_proto_rawDesc)))
	})
	return file_proto_proto_retain_retain_proto_rawDescData
}

var file_proto_proto_retain_retain_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_proto_retain_retain_proto_goTypes = []any{
	(*RetainMessage)(nil), // 0: proto.RetainMessage
}
var file_proto_proto_retain_retain_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_retain_retain_proto_init() }
func file_proto_proto_retain_retain_proto_init() {
	if File_proto_proto_retain_retain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_retain_retain_proto_rawDesc), len(file_proto_proto_retain_retain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_retain_retain_proto_goTypes,
		DependencyIndexes: file_proto_proto_retain_retain_proto_depIdxs,
		MessageInfos:      file_proto_proto_retain_retain_proto_msgTypes,
	}.Build()
	File_proto_proto_retain_retain_proto = out.File
	file_proto_proto_retain_retain_proto_goTypes = nil
	file_proto_proto_retain_retain_proto_depIdxs = nil
}
