// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/broker/publish/publishpb/message.proto

package publishpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorePublishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageID     string                 `protobuf:"bytes,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	PublishPacket []byte                 `protobuf:"bytes,2,opt,name=PublishPacket,proto3" json:"PublishPacket,omitempty"`
	PubReceived   bool                   `protobuf:"varint,3,opt,name=PubReceived,proto3" json:"PubReceived,omitempty"`
	CreatedTime   int64                  `protobuf:"varint,4,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"`
	ExpiredTime   int64                  `protobuf:"varint,5,opt,name=ExpiredTime,proto3" json:"ExpiredTime,omitempty"`
	SenderID      string                 `protobuf:"bytes,6,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorePublishMessage) Reset() {
	*x = StorePublishMessage{}
	mi := &file_pkg_broker_publish_publishpb_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePublishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePublishMessage) ProtoMessage() {}

func (x *StorePublishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_broker_publish_publishpb_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePublishMessage.ProtoReflect.Descriptor instead.
func (*StorePublishMessage) Descriptor() ([]byte, []int) {
	return file_pkg_broker_publish_publishpb_message_proto_rawDescGZIP(), []int{0}
}

func (x *StorePublishMessage) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *StorePublishMessage) GetPublishPacket() []byte {
	if x != nil {
		return x.PublishPacket
	}
	return nil
}

func (x *StorePublishMessage) GetPubReceived() bool {
	if x != nil {
		return x.PubReceived
	}
	return false
}

func (x *StorePublishMessage) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *StorePublishMessage) GetExpiredTime() int64 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

func (x *StorePublishMessage) GetSenderID() string {
	if x != nil {
		return x.SenderID
	}
	return ""
}

type BatchStorePublishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []*StorePublishMessage `protobuf:"bytes,1,rep,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStorePublishMessage) Reset() {
	*x = BatchStorePublishMessage{}
	mi := &file_pkg_broker_publish_publishpb_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStorePublishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStorePublishMessage) ProtoMessage() {}

func (x *BatchStorePublishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_broker_publish_publishpb_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStorePublishMessage.ProtoReflect.Descriptor instead.
func (*BatchStorePublishMessage) Descriptor() ([]byte, []int) {
	return file_pkg_broker_publish_publishpb_message_proto_rawDescGZIP(), []int{1}
}

func (x *BatchStorePublishMessage) GetMessage() []*StorePublishMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_pkg_broker_publish_publishpb_message_proto protoreflect.FileDescriptor

const file_pkg_broker_publish_publishpb_message_proto_rawDesc = "" +
	"\n" +
	"*pkg/broker/publish/publishpb/message.proto\x12\tpublishpb\"\xdb\x01\n" +
	"\x13StorePublishMessage\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\tR\tMessageID\x12$\n" +
	"\rPublishPacket\x18\x02 \x01(\fR\rPublishPacket\x12 \n" +
	"\vPubReceived\x18\x03 \x01(\bR\vPubReceived\x12 \n" +
	"\vCreatedTime\x18\x04 \x01(\x03R\vCreatedTime\x12 \n" +
	"\vExpiredTime\x18\x05 \x01(\x03R\vExpiredTime\x12\x1a\n" +
	"\bSenderID\x18\x06 \x01(\tR\bSenderID\"T\n" +
	"\x18BatchStorePublishMessage\x128\n" +
	"\aMessage\x18\x01 \x03(\v2\x1e.publishpb.StorePublishMessageR\aMessageBBZ@github.com/BAN1ce/skyTree/pkg/broker/publish/publishpb;publishpbb\x06proto3"

var (
	file_pkg_broker_publish_publishpb_message_proto_rawDescOnce sync.Once
	file_pkg_broker_publish_publishpb_message_proto_rawDescData []byte
)

func file_pkg_broker_publish_publishpb_message_proto_rawDescGZIP() []byte {
	file_pkg_broker_publish_publishpb_message_proto_rawDescOnce.Do(func() {
		file_pkg_broker_publish_publishpb_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_broker_publish_publishpb_message_proto_rawDesc), len(file_pkg_broker_publish_publishpb_message_proto_rawDesc)))
	})
	return file_pkg_broker_publish_publishpb_message_proto_rawDescData
}

var file_pkg_broker_publish_publishpb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_broker_publish_publishpb_message_proto_goTypes = []any{
	(*StorePublishMessage)(nil),      // 0: publishpb.StorePublishMessage
	(*BatchStorePublishMessage)(nil), // 1: publishpb.BatchStorePublishMessage
}
var file_pkg_broker_publish_publishpb_message_proto_depIdxs = []int32{
	0, // 0: publishpb.BatchStorePublishMessage.Message:type_name -> publishpb.StorePublishMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_broker_publish_publishpb_message_proto_init() }
func file_pkg_broker_publish_publishpb_message_proto_init() {
	if File_pkg_broker_publish_publishpb_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_broker_publish_publishpb_message_proto_rawDesc), len(file_pkg_broker_publish_publishpb_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_broker_publish_publishpb_message_proto_goTypes,
		DependencyIndexes: file_pkg_broker_publish_publishpb_message_proto_depIdxs,
		MessageInfos:      file_pkg_broker_publish_publishpb_message_proto_msgTypes,
	}.Build()
	File_pkg_broker_publish_publishpb_message_proto = out.File
	file_pkg_broker_publish_publishpb_message_proto_goTypes = nil
	file_pkg_broker_publish_publishpb_message_proto_depIdxs = nil
}
